// ─── items.axn ─────────────────────────────────────────
// Generated by Axon v0.7.0 transpiler
// DO NOT EDIT — source: .axn


// ── Axon v0.4.0 stdlib ──────────────────────────────────────────────────────

/**
 * Apply fn to every element of xs and return the results.
 * @pure @total
 * @param {Array} xs
 * @param {Function} fn
 * @returns {Array}
 */
const map = (xs, fn) => xs.map(fn);

/**
 * Keep only elements of xs for which pred returns true.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {Array}
 */
const filter = (xs, pred) => xs.filter(pred);

/**
 * Reduce xs to a single value, starting from init.
 * @pure @total
 * @param {Array} xs
 * @param {*} init
 * @param {Function} fn
 * @returns {*}
 */
const fold = (xs, init, fn) => xs.reduce(fn, init);

/**
 * Apply a sequence of single-argument functions left to right.
 * @pure @total
 * @param {...Function} fns
 * @returns {Function}
 */
const pipe = (...fns) => (x) => fns.reduce((v, f) => f(v), x);

/**
 * Combine two arrays element-by-element into pairs.
 * @pure @total
 * @param {Array} xs
 * @param {Array} ys
 * @returns {Array}
 */
const zip = (xs, ys) => xs.map((x, i) => [x, ys[i]]);

/**
 * Produce an array of integers from start (inclusive) to end (exclusive).
 * @pure @total
 * @param {number} start
 * @param {number} end
 * @returns {number[]}
 */
const range = (start, end) => Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);

/**
 * Return the first element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const first = (xs) => xs[0];

/**
 * Return the last element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const last = (xs) => xs[xs.length - 1];

/**
 * Sum a numeric array.
 * @pure @total
 * @param {number[]} xs
 * @returns {number}
 */
const sum = (xs) => xs.reduce((a, b) => a + b, 0);

/**
 * Count elements matching pred, or total length if no pred given.
 * @pure @total
 * @param {Array} xs
 * @param {Function} [pred]
 * @returns {number}
 */
const count = (xs, pred) => pred ? xs.filter(pred).length : xs.length;

/**
 * True if any element satisfies pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const any = (xs, pred) => xs.some(pred);

/**
 * True if all elements satisfy pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const all = (xs, pred) => xs.every(pred);

/**
 * Flatten one level of nesting.
 * @pure @total
 * @param {Array} xs
 * @returns {Array}
 */
const flat = (xs) => xs.flat();

/**
 * Group an array into a Map by key function.
 * @pure @total
 * @param {Array} xs
 * @param {Function} keyFn
 * @returns {Map}
 */
const groupBy = (xs, keyFn) => xs.reduce((m, x) => {
  const k = keyFn(x);
  if (!m.has(k)) m.set(k, []);
  m.get(k).push(x);
  return m;
}, new Map());

/**
 * Return a new object with only the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const pick = (obj, keys) => Object.fromEntries(keys.filter(k => k in obj).map(k => [k, obj[k]]));

/**
 * Return a new object without the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const omit = (obj, keys) => Object.fromEntries(Object.entries(obj).filter(([k]) => !keys.includes(k)));

// ── Axon built-in constraint validators ─────────────────────────────────────
// Generated by 'type T = base where ...' declarations.

const __axon_presets = {
  email:   /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  url:     /^https?:\/\//,
  uuid:    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  alpha:   /^[a-zA-Z]+$/,
  alnum:   /^[a-zA-Z0-9]+$/,
  numeric: /^[0-9]+$/,
  slug:    /^[a-z0-9-]+$/,
  hex:     /^#?[0-9a-fA-F]{3,8}$/,
};

// ── Axon v0.6.0 Result type ──────────────────────────────────────────────────
// Result<T> = Ok { value: T } | Err { message: string }
// Constructors and helpers available in every Axon program.

/**
 * Wrap a value in Ok. Use as the success return of a @throws function.
 * @pure @total
 * @param {*} value
 * @returns {{ tag: 'Ok', value: * }}
 */
const ok = (value) => ({ tag: 'Ok', value });

/**
 * Wrap a message in Err. Use as the failure return of a @throws function.
 * @pure @total
 * @param {string} message
 * @returns {{ tag: 'Err', message: string }}
 */
const err = (message) => ({ tag: 'Err', message });

/**
 * True if result is Ok.
 * @pure @total
 * @param {{ tag: string }} r
 * @returns {boolean}
 */
const is_ok = (r) => r != null && r.tag === 'Ok';

/**
 * True if result is Err.
 * @pure @total
 * @param {{ tag: string }} r
 * @returns {boolean}
 */
const is_err = (r) => r != null && r.tag === 'Err';

/**
 * Unwrap Ok value — throws if Err.
 * @param {{ tag: string, value: *, message: string }} r
 * @returns {*}
 */
const unwrap = (r) => {
  if (r != null && r.tag === 'Ok') return r.value;
  throw new Error(r != null ? r.message : 'unwrap called on null');
};

/**
 * Unwrap Ok value, or return fallback if Err.
 * @pure @total
 * @param {{ tag: string, value: * }} r
 * @param {*} fallback
 * @returns {*}
 */
const unwrap_or = (r, fallback) => (r != null && r.tag === 'Ok') ? r.value : fallback;

// ── Axon v0.4.0 test runner ──────────────────────────────────────────────────
// @test declarations push entries here. Call __runAxonTests() to execute them.
// Also exposed on globalThis so the CLI's vm context can access it.

const __axon_tests = [];

/**
 * Run all registered @test declarations. Returns a result summary.
 * @returns {{ passed: number, failed: number, total: number, results: Array }}
 */
const __runAxonTests = () => {
  let passed = 0, failed = 0;
  const results = [];
  for (const t of __axon_tests) {
    try {
      const ok = !!t.fn();
      if (ok) {
        passed++;
        results.push({ ok: true,  desc: t.desc });
      } else {
        failed++;
        results.push({ ok: false, desc: t.desc, error: 'assertion returned false' });
      }
    } catch(e) {
      failed++;
      results.push({ ok: false, desc: t.desc, error: String(e) });
    }
  }
  return { passed, failed, total: passed + failed, results };
};
// Expose on globalThis so the Node CLI vm context and browser window can both access it
if (typeof globalThis !== 'undefined') {
  globalThis.__axon_tests = __axon_tests;
  globalThis.__runAxonTests = __runAxonTests;
}

/** @interface Tradeable
 * @property {string} name
 * @property {number} price
 * @property {string} rarity
 * @property {function(): string} describe
 */

/** @interface Filterable<T>
 * @property {function(T): boolean} matches
 */

// Tagged union: Category
const Weapon = Object.freeze({ tag: "Weapon" });
const Armor = Object.freeze({ tag: "Armor" });
const Potion = Object.freeze({ tag: "Potion" });
const Relic = Object.freeze({ tag: "Relic" });
const Scroll = Object.freeze({ tag: "Scroll" });

/** @typedef {{
 *   name: string,
 *   category: Category,
 *   rarity: string,
 *   price: number,
 *   power: number,
 *   lore: string
 * }} Item
 */

const keep_if = (items, pred) => items.filter(pred);

const transform = (items, f) => items.map(f);

const order_by = (items, key) => items.slice().sort((a, b) => {
  let ka = key(a);
  let kb = key(b);
  if (ka < kb) {
    return -1;
  } else if (ka > kb) {
    return 1;
  } else {
    return 0;
  }
});

const order_by_desc = (items, key) => items.slice().sort((a, b) => {
  let ka = key(a);
  let kb = key(b);
  if (ka > kb) {
    return -1;
  } else if (ka < kb) {
    return 1;
  } else {
    return 0;
  }
});

/**
 * @param {T[]} items
 * @param {function(T): number} value_of
 * @returns {number}
 */
const total = (items, value_of) => {
  let acc = 0;
  for (const item of items) {
    acc = acc + value_of(item);
  }
  return acc;
};

const rarity_rank = (r) => ((_m) => (_m === "Common") ? 1 : (_m === "Uncommon") ? 2 : (_m === "Rare") ? 3 : (_m === "Epic") ? 4 : (_m === "Legendary") ? 5 : 0)(r);

const rarity_color = (r) => ((_m) => (_m === "Common") ? "#aaaaaa" : (_m === "Uncommon") ? "#1eff00" : (_m === "Rare") ? "#0070dd" : (_m === "Epic") ? "#a335ee" : (_m === "Legendary") ? "#ff8000" : "#ffffff")(r);

const category_icon = (c) => ((_m) => (_m.tag === "Weapon") ? "⚔️" : (_m.tag === "Armor") ? "🛡️" : (_m.tag === "Potion") ? "⚗️" : (_m.tag === "Relic") ? "💎" : (_m.tag === "Scroll") ? "📜" : undefined)(c);

const category_name = (c) => ((_m) => (_m.tag === "Weapon") ? "Weapon" : (_m.tag === "Armor") ? "Armor" : (_m.tag === "Potion") ? "Potion" : (_m.tag === "Relic") ? "Relic" : (_m.tag === "Scroll") ? "Scroll" : undefined)(c);

/**
 * @param {Item[]} items
 * @param {string} cat
 * @returns {Item[]}
 */
const by_category = (items, cat) => {
  if (cat == "All") {
    return items;
  } else {
    return items.filter(item => category_name(item.category) == cat);
  }
};

/**
 * @param {Item[]} items
 * @param {string} rar
 * @returns {Item[]}
 */
const by_rarity = (items, rar) => {
  if (rar == "All") {
    return items;
  } else {
    return items.filter(item => item.rarity == rar);
  }
};

/**
 * @param {Item[]} items
 * @param {number} max
 * @returns {Item[]}
 */
const by_max_price = (items, max) => {
  if (max <= 0) {
    return items;
  } else {
    return items.filter(item => item.price <= max);
  }
};

/**
 * @param {Item[]} items
 * @param {string} query
 * @returns {Item[]}
 */
const search_items = (items, query) => {
  if (query == "") {
    return items;
  } else {
    let q = query.toLowerCase();
    return items.filter(item => item.name.toLowerCase().includes(q) || item.lore.toLowerCase().includes(q));
  }
};

const describe_item = (item) => category_icon(item.category) + " " + item.name + " [" + item.rarity + "] — " + item.price + "g";

const cart_total = (items) => total(items, item => item.price);

__axon_tests.push({ desc: "rarity_rank orders correctly", fn: () => rarity_rank("Legendary") > rarity_rank("Common") });

__axon_tests.push({ desc: "rarity_rank unknown returns 0", fn: () => rarity_rank("Mythic") == 0 });

__axon_tests.push({ desc: "category_icon returns emoji", fn: () => category_icon(Weapon) == "⚔️" });

__axon_tests.push({ desc: "category_name returns string", fn: () => category_name(Potion) == "Potion" });

__axon_tests.push({ desc: "keep_if filters by predicate", fn: () => keep_if([1, 2, 3, 4], x => x > 2).length == 2 });

__axon_tests.push({ desc: "transform applies function", fn: () => transform([1, 2, 3], x => x * 2)[2] == 6 });

__axon_tests.push({ desc: "order_by sorts ascending", fn: () => order_by([3, 1, 2], x => x)[0] == 1 });

__axon_tests.push({ desc: "order_by_desc sorts descending", fn: () => order_by_desc([3, 1, 2], x => x)[0] == 3 });

__axon_tests.push({ desc: "total sums values", fn: () => total([1, 2, 3], x => x) == 6 });

__axon_tests.push({ desc: "let infer on item transform", fn: () => (() => {
  let names = transform([{ name: "Sword" }, { name: "Bow" }], i => i.name);
  return names[0] == "Sword";
})() });

__axon_tests.push({ desc: "by_category All returns all", fn: () => by_category([{ name: "x", category: Weapon, rarity: "Common", price: 10, power: 5, lore: "" }], "All").length == 1 });

__axon_tests.push({ desc: "search_items finds by name", fn: () => (() => {
  let items = [{
  name: "Iron Sword",
  category: Weapon,
  rarity: "Common",
  price: 40,
  power: 12,
  lore: "reliable"
}];
  return search_items(items, "sword").length == 1;
})() });

__axon_tests.push({ desc: "search_items empty query returns all", fn: () => (() => {
  let items = [{
  name: "Iron Sword",
  category: Weapon,
  rarity: "Common",
  price: 40,
  power: 12,
  lore: ""
}];
  return search_items(items, "").length == 1;
})() });

__axon_tests.push({ desc: "cart_total sums item prices", fn: () => cart_total([{
  name: "A",
  category: Weapon,
  rarity: "Common",
  price: 100,
  power: 10,
  lore: ""
}, { name: "B", category: Potion, rarity: "Common", price: 50, power: 5, lore: "" }]) == 150 });


// ─── catalog.axn ───────────────────────────────────────
// Generated by Axon v0.7.0 transpiler
// DO NOT EDIT — source: .axn


const get_catalog = () => [{
  name: "Iron Sword",
  category: Weapon,
  rarity: "Common",
  price: 40,
  power: 12,
  lore: "A standard blade, well-worn but reliable."
}, {
  name: "Serpent Fang",
  category: Weapon,
  rarity: "Uncommon",
  price: 120,
  power: 28,
  lore: "Said to carry a venom that slows the mind."
}, {
  name: "Stormcaller Axe",
  category: Weapon,
  rarity: "Rare",
  price: 380,
  power: 55,
  lore: "Crackling with static, it calls lightning on a crit."
}, {
  name: "Dawnbreaker",
  category: Weapon,
  rarity: "Epic",
  price: 950,
  power: 88,
  lore: "Forged at first light, it burns undead on contact."
}, {
  name: "Worldender",
  category: Weapon,
  rarity: "Legendary",
  price: 4200,
  power: 140,
  lore: "No chronicle speaks of who first unsheathed it."
}, {
  name: "Leather Vest",
  category: Armor,
  rarity: "Common",
  price: 35,
  power: 8,
  lore: "Light and breathable. Smells faintly of mead."
}, {
  name: "Chain Hauberk",
  category: Armor,
  rarity: "Uncommon",
  price: 110,
  power: 22,
  lore: "Rattles on stairs. Very effective, very loud."
}, {
  name: "Shadowweave Cloak",
  category: Armor,
  rarity: "Rare",
  price: 420,
  power: 40,
  lore: "Absorbs faint light. Rogues pay triple for these."
}, {
  name: "Aegis of the Fallen",
  category: Armor,
  rarity: "Epic",
  price: 1100,
  power: 75,
  lore: "Carved with the names of the seven lost kingdoms."
}, {
  name: "Minor Healing",
  category: Potion,
  rarity: "Common",
  price: 15,
  power: 20,
  lore: "Tastes of copper. Works on most wounds."
}, {
  name: "Swiftfoot Draught",
  category: Potion,
  rarity: "Uncommon",
  price: 55,
  power: 0,
  lore: "Doubles movement speed for one hour. Side-effects: hiccups."
}, {
  name: "Greater Elixir",
  category: Potion,
  rarity: "Rare",
  price: 200,
  power: 60,
  lore: "Used by healers who have run out of spells."
}, {
  name: "Phoenix Tears",
  category: Potion,
  rarity: "Legendary",
  price: 2800,
  power: 999,
  lore: "Said to pull souls back from the other shore."
}, {
  name: "Lucky Coin",
  category: Relic,
  rarity: "Common",
  price: 60,
  power: 5,
  lore: "Warm to the touch. Never lands on tails."
}, {
  name: "Whispering Orb",
  category: Relic,
  rarity: "Uncommon",
  price: 150,
  power: 18,
  lore: "Murmurs weather forecasts in an unknown language."
}, {
  name: "Eye of Eternity",
  category: Relic,
  rarity: "Epic",
  price: 1500,
  power: 65,
  lore: "Grants true sight. The price is one real eye."
}, {
  name: "Shard of the Abyss",
  category: Relic,
  rarity: "Legendary",
  price: 5000,
  power: 200,
  lore: "Cold. Always cold. Even in fire."
}, {
  name: "Torch Scroll",
  category: Scroll,
  rarity: "Common",
  price: 20,
  power: 10,
  lore: "Casts a small light. Very popular in dungeons."
}, {
  name: "Scroll of Binding",
  category: Scroll,
  rarity: "Uncommon",
  price: 90,
  power: 30,
  lore: "Roots an enemy in place for three breaths."
}, {
  name: "Tome of Unmaking",
  category: Scroll,
  rarity: "Rare",
  price: 500,
  power: 70,
  lore: "Erases one object from history. One use only."
}];


// ─── main.axn ──────────────────────────────────────────
// Generated by Axon v0.7.0 transpiler
// DO NOT EDIT — source: .axn



/** @typedef {{
 *   all_items: Item[],
 *   cart: Item[],
 *   filter_cat: string,
 *   filter_rar: string,
 *   sort_key: string,
 *   search: string
 * }} AppState
 */

const make_state = () => ({
  all_items: get_catalog(),
  cart: [],
  filter_cat: "All",
  filter_rar: "All",
  sort_key: "price_asc",
  search: ""
});

/**
 * @param {AppState} state
 * @returns {Item[]}
 */
const apply_filters = (state) => {
  let items = state.all_items;
  let a = by_category(items, state.filter_cat);
  let b = by_rarity(a, state.filter_rar);
  let c = search_items(b, state.search);
  let sorted = apply_sort(c, state.sort_key);
  return sorted;
};

const apply_sort = (items, sort) => ((_m) => (_m === "price_asc") ? order_by(items, i => i.price) : (_m === "price_desc") ? order_by_desc(items, i => i.price) : (_m === "power_desc") ? order_by_desc(items, i => i.power) : (_m === "rarity_desc") ? order_by_desc(items, i => rarity_rank(i.rarity)) : (_m === "name_asc") ? order_by(items, i => i.name) : items)(sort);

const is_in_cart = (state, item) => state.cart.some(c => c.name == item.name);

const el = (id) => document.getElementById(id);

const set_count = (id, n) => el(id).textContent = n + "";

/**
 * @param {AppState} state
 * @returns {void}
 */
const render = (state) => {
  let visible = apply_filters(state);
  render_grid(state, visible);
  render_cart(state);
  return render_stats(state, visible);
};

/**
 * @param {AppState} state
 * @param {Item[]} visible
 * @returns {void}
 */
const render_stats = (state, visible) => {
  el("result-count").textContent = visible.length + " items";
  el("cart-total").textContent = cart_total(state.cart) + "g";
  return el("cart-count").textContent = state.cart.length + "";
};

/**
 * @param {AppState} state
 * @param {Item[]} items
 * @returns {void}
 */
const render_grid = (state, items) => {
  if (items.length == 0) {
    return el("item-grid").innerHTML = "<div class=\"empty-state\">No items match your search.</div>";
  } else {
    let cards = transform(items, item => item_card_html(state, item));
    return el("item-grid").innerHTML = cards.join("");
  }
};

/**
 * @param {AppState} state
 * @param {Item} item
 * @returns {string}
 */
const item_card_html = (state, item) => {
  let color = rarity_color(item.rarity);
  let icon = category_icon(item.category);
  let in_cart = is_in_cart(state, item);
  let btn_cls = in_cart ? "btn-in-cart" : "btn-buy";
  let btn_txt = in_cart ? "✓ In Cart" : "Add to Cart";
  let badge = "<span class=\"rarity-badge\" style=\"color:" + color + ";border-color:" + color + "\">" + item.rarity + "</span>";
  return "<div class=\"item-card\">" + "<div class=\"item-header\">" + "<span class=\"item-icon\">" + icon + "</span>" + "<div class=\"item-title\">" + "<div class=\"item-name\">" + item.name + "</div>" + badge + "</div>" + "</div>" + "<div class=\"item-lore\">" + item.lore + "</div>" + "<div class=\"item-footer\">" + "<div class=\"item-stats\">" + "<span class=\"stat-price\">💰 " + item.price + "g</span>" + "<span class=\"stat-power\">⚡ " + item.power + "</span>" + "</div>" + "<button class=\"" + btn_cls + "\" onclick=\"bazaarBuy('" + item.name + "')\">" + btn_txt + "</button>" + "</div>" + "</div>";
};

/**
 * @param {AppState} state
 * @returns {void}
 */
const render_cart = (state) => {
  if (state.cart.length == 0) {
    return el("cart-items").innerHTML = "<div class=\"cart-empty\">Your cart is empty.</div>";
  } else {
    let rows = transform(state.cart, item => "<div class=\"cart-row\">" + "<span class=\"cart-item-name\">" + category_icon(item.category) + " " + item.name + "</span>" + "<span class=\"cart-item-price\">" + item.price + "g</span>" + "<button class=\"cart-remove\" onclick=\"bazaarRemove('" + item.name + "')\">✕</button>" + "</div>");
    return el("cart-items").innerHTML = rows.join("");
  }
};

let state = make_state();

/**
 * @param {string} name
 * @returns {void}
 */
const buy_item = (name) => {
  let item_arr = state.all_items.filter(i => i.name == name);
  if (item_arr.length > 0) {
    let item = item_arr[0];
    if (is_in_cart(state, item)) {
      return state = {
  all_items: state.all_items,
  cart: state.cart.filter(c => c.name != name),
  filter_cat: state.filter_cat,
  filter_rar: state.filter_rar,
  sort_key: state.sort_key,
  search: state.search
};
    } else {
      return state = {
  all_items: state.all_items,
  cart: state.cart.concat([item]),
  filter_cat: state.filter_cat,
  filter_rar: state.filter_rar,
  sort_key: state.sort_key,
  search: state.search
};
    }
    return render(state);
  }
};

/**
 * @param {string} name
 * @returns {void}
 */
const remove_item = (name) => {
  state = {
  all_items: state.all_items,
  cart: state.cart.filter(c => c.name != name),
  filter_cat: state.filter_cat,
  filter_rar: state.filter_rar,
  sort_key: state.sort_key,
  search: state.search
};
  return render(state);
};

/**
 * @returns {void}
 */
const on_filter_change = () => {
  let cat = el("filter-cat").value;
  let rar = el("filter-rar").value;
  let srt = el("sort-select").value;
  let q = el("search-box").value;
  state = {
  all_items: state.all_items,
  cart: state.cart,
  filter_cat: cat,
  filter_rar: rar,
  sort_key: srt,
  search: q
};
  return render(state);
};

/**
 * @returns {void}
 */
const clear_cart = () => {
  state = {
  all_items: state.all_items,
  cart: [],
  filter_cat: state.filter_cat,
  filter_rar: state.filter_rar,
  sort_key: state.sort_key,
  search: state.search
};
  return render(state);
};

window.bazaarBuy = buy_item;

window.bazaarRemove = remove_item;

window.onFilterChange = on_filter_change;

window.clearCart = clear_cart;

render(state);

