// ─── main.axn ──────────────────────────────────────────
// Generated by Axon v0.8.0 transpiler
// DO NOT EDIT — source: .axn


// ── Axon v0.4.0 stdlib ──────────────────────────────────────────────────────

/**
 * Apply fn to every element of xs and return the results.
 * @pure @total
 * @param {Array} xs
 * @param {Function} fn
 * @returns {Array}
 */
const map = (xs, fn) => xs.map(fn);

/**
 * Keep only elements of xs for which pred returns true.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {Array}
 */
const filter = (xs, pred) => xs.filter(pred);

/**
 * Reduce xs to a single value, starting from init.
 * @pure @total
 * @param {Array} xs
 * @param {*} init
 * @param {Function} fn
 * @returns {*}
 */
const fold = (xs, init, fn) => xs.reduce(fn, init);

/**
 * Apply a sequence of single-argument functions left to right.
 * @pure @total
 * @param {...Function} fns
 * @returns {Function}
 */
const pipe = (...fns) => (x) => fns.reduce((v, f) => f(v), x);

/**
 * Combine two arrays element-by-element into pairs.
 * @pure @total
 * @param {Array} xs
 * @param {Array} ys
 * @returns {Array}
 */
const zip = (xs, ys) => xs.map((x, i) => [x, ys[i]]);

/**
 * Produce an array of integers from start (inclusive) to end (exclusive).
 * @pure @total
 * @param {number} start
 * @param {number} end
 * @returns {number[]}
 */
const range = (start, end) => Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);

/**
 * Return the first element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const first = (xs) => xs[0];

/**
 * Return the last element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const last = (xs) => xs[xs.length - 1];

/**
 * Sum a numeric array.
 * @pure @total
 * @param {number[]} xs
 * @returns {number}
 */
const sum = (xs) => xs.reduce((a, b) => a + b, 0);

/**
 * Count elements matching pred, or total length if no pred given.
 * @pure @total
 * @param {Array} xs
 * @param {Function} [pred]
 * @returns {number}
 */
const count = (xs, pred) => pred ? xs.filter(pred).length : xs.length;

/**
 * True if any element satisfies pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const any = (xs, pred) => xs.some(pred);

/**
 * True if all elements satisfy pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const all = (xs, pred) => xs.every(pred);

/**
 * Flatten one level of nesting.
 * @pure @total
 * @param {Array} xs
 * @returns {Array}
 */
const flat = (xs) => xs.flat();

/**
 * Group an array into a Map by key function.
 * @pure @total
 * @param {Array} xs
 * @param {Function} keyFn
 * @returns {Map}
 */
const groupBy = (xs, keyFn) => xs.reduce((m, x) => {
  const k = keyFn(x);
  if (!m.has(k)) m.set(k, []);
  m.get(k).push(x);
  return m;
}, new Map());

/**
 * Return a new object with only the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const pick = (obj, keys) => Object.fromEntries(keys.filter(k => k in obj).map(k => [k, obj[k]]));

/**
 * Return a new object without the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const omit = (obj, keys) => Object.fromEntries(Object.entries(obj).filter(([k]) => !keys.includes(k)));

// ── Axon built-in constraint validators ─────────────────────────────────────
// Generated by 'type T = base where ...' declarations.

const __axon_presets = {
  email:   /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  url:     /^https?:\/\//,
  uuid:    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  alpha:   /^[a-zA-Z]+$/,
  alnum:   /^[a-zA-Z0-9]+$/,
  numeric: /^[0-9]+$/,
  slug:    /^[a-z0-9-]+$/,
  hex:     /^#?[0-9a-fA-F]{3,8}$/,
};

// ── Axon v0.6.0 Result type ──────────────────────────────────────────────────
// Result<T> = Ok { value: T } | Err { message: string }
// Constructors and helpers available in every Axon program.

/**
 * Wrap a value in Ok. Use as the success return of a @throws function.
 * @pure @total
 * @param {*} value
 * @returns {{ tag: 'Ok', value: * }}
 */
const ok = (value) => ({ tag: 'Ok', value });

/**
 * Wrap a message in Err. Use as the failure return of a @throws function.
 * @pure @total
 * @param {string} message
 * @returns {{ tag: 'Err', message: string }}
 */
const err = (message) => ({ tag: 'Err', message });

/**
 * True if result is Ok.
 * @pure @total
 * @param {{ tag: string }} r
 * @returns {boolean}
 */
const is_ok = (r) => r != null && r.tag === 'Ok';

/**
 * True if result is Err.
 * @pure @total
 * @param {{ tag: string }} r
 * @returns {boolean}
 */
const is_err = (r) => r != null && r.tag === 'Err';

/**
 * Unwrap Ok value — throws if Err.
 * @param {{ tag: string, value: *, message: string }} r
 * @returns {*}
 */
const unwrap = (r) => {
  if (r != null && r.tag === 'Ok') return r.value;
  throw new Error(r != null ? r.message : 'unwrap called on null');
};

/**
 * Unwrap Ok value, or return fallback if Err.
 * @pure @total
 * @param {{ tag: string, value: * }} r
 * @param {*} fallback
 * @returns {*}
 */
const unwrap_or = (r, fallback) => (r != null && r.tag === 'Ok') ? r.value : fallback;

// ── Axon v0.8.0 Async helpers ────────────────────────────────────────────────

/**
 * Return a Promise that resolves after ms milliseconds.
 * Use with await inside async fn declarations.
 * @param {number} ms  Duration in milliseconds
 * @returns {Promise<void>}
 */
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// ── Axon v0.4.0 test runner ──────────────────────────────────────────────────
// @test declarations push entries here. Call __runAxonTests() to execute them.
// Also exposed on globalThis so the CLI's vm context can access it.

const __axon_tests = [];

/**
 * Run all registered @test declarations. Returns a result summary.
 * @returns {{ passed: number, failed: number, total: number, results: Array }}
 */
const __runAxonTests = () => {
  let passed = 0, failed = 0;
  const results = [];
  for (const t of __axon_tests) {
    try {
      const ok = !!t.fn();
      if (ok) {
        passed++;
        results.push({ ok: true,  desc: t.desc });
      } else {
        failed++;
        results.push({ ok: false, desc: t.desc, error: 'assertion returned false' });
      }
    } catch(e) {
      failed++;
      results.push({ ok: false, desc: t.desc, error: String(e) });
    }
  }
  return { passed, failed, total: passed + failed, results };
};
// Expose on globalThis so the Node CLI vm context and browser window can both access it
if (typeof globalThis !== 'undefined') {
  globalThis.__axon_tests = __axon_tests;
  globalThis.__runAxonTests = __runAxonTests;
}

/** @store Kingdom — reactive state boundary (v0.8) */
const Kingdom = (() => {
  let _state = { day: 1, season: "spring", weather: "clear", events: [], running: false, speed: 900 };
  const _subs = [];
  return {
    get day() { return _state.day; },
    get season() { return _state.season; },
    get weather() { return _state.weather; },
    get events() { return _state.events; },
    get running() { return _state.running; },
    get speed() { return _state.speed; },
    set(patch) {
      _state = Object.assign({}, _state, patch);
      for (const __fn of _subs) __fn(_state);
    },
    subscribe(fn) { _subs.push(fn); fn(_state); },
  };
})();

/**
 * @pure — no side effects
 * @param {number} day
 * @returns {string}
 */
const season_for = (day) => {
  let idx = Math.floor(day / 91) % 4;
  if (idx == 0) {
    return "spring";
  } else if (idx == 1) {
    return "summer";
  } else if (idx == 2) {
    return "autumn";
  } else {
    return "winter";
  }
};

/**
 * @pure — no side effects
 * @param {number} day
 * @param {string} season
 * @returns {string}
 */
const weather_for = (day, season) => {
  let seed = (day * 2654435761 + 7) % 100;
  return ((_m) => (_m === "winter") ? seed < 45 ? "snow" : seed < 75 ? "frost" : "blizzard" : (_m === "summer") ? seed < 50 ? "clear" : seed < 80 ? "haze" : "drought" : (_m === "spring") ? seed < 40 ? "rain" : seed < 70 ? "clear" : "fog" : seed < 50 ? "clear" : "cloudy")(season);
};

/**
 * @pure — no side effects
 * @param {number} day
 * @param {string} weather
 * @returns {string}
 */
const event_for = (day, weather) => {
  let seed = (day * 1103515245 + 12345) % 14;
  let base = ((_m) => (_m === 0) ? "A merchant caravan arrived bearing exotic spices" : (_m === 1) ? "The blacksmith forged a blade of legendary steel" : (_m === 2) ? "Scouts reported strange lights in the northern woods" : (_m === 3) ? "The harvest exceeded all expectations" : (_m === 4) ? "A traveling bard performed tales of the old wars" : (_m === 5) ? "The council passed new trade agreements" : (_m === 6) ? "A dragon silhouette crossed the mountain pass" : (_m === 7) ? "The healers guild opened their doors to the poor" : (_m === 8) ? "A grand feast was held in the keep" : (_m === 9) ? "The watchtower bell rang — riders approach" : (_m === 10) ? "A stranger arrived at the inn with an unusual map" : (_m === 11) ? "The kingdom's coffers grew with a fresh tax levy" : (_m === 12) ? "A temple ceremony drew pilgrims from distant lands" : "The kingdom rested in an unusual quiet")(seed);
  return ((_m) => (_m === "snow") ? base + " — braving the heavy snowfall" : (_m === "rain") ? base + " — beneath relentless rain" : (_m === "drought") ? base + " — under the scorching drought" : (_m === "blizzard") ? base + " — through a raging blizzard" : base)(weather);
};

const season_icon = (season) => ((_m) => (_m === "spring") ? "🌸" : (_m === "summer") ? "☀️" : (_m === "autumn") ? "🍂" : (_m === "winter") ? "❄️" : "🌍")(season);

const weather_icon = (weather) => ((_m) => (_m === "clear") ? "☀️" : (_m === "rain") ? "🌧" : (_m === "snow") ? "❄️" : (_m === "fog") ? "🌫" : (_m === "frost") ? "🧊" : (_m === "haze") ? "🌫" : (_m === "blizzard") ? "🌨" : (_m === "drought") ? "🌵" : "🌤")(weather);

/**
 * @async
 * @effects timer
 * @returns {*}
 */
const tick = async () => {
  if (!Kingdom.running) {
    return undefined;
  }
  let next_day = Kingdom.day + 1;
  let next_season = season_for(next_day);
  let next_weather = weather_for(next_day, next_season);
  let event = event_for(next_day, next_weather);
  let prev = Kingdom.events;
  let next_events = [event, ...prev].slice(0, 10);
  Kingdom.set({
  day: next_day,
  season: next_season,
  weather: next_weather,
  events: next_events
});
  await delay(Kingdom.speed);
  tick();
  return undefined;
};

/**
 * @returns {*}
 */
const start = () => {
  Kingdom.set({ running: true, events: [] });
  tick();
  return undefined;
};

/**
 * @returns {*}
 */
const pause = () => Kingdom.set({ running: false });

/**
 * @param {number} ms
 * @returns {*}
 */
const set_speed = (ms) => Kingdom.set({ speed: ms });

/**
 * @returns {*}
 */
const render = () => {
  let day = Kingdom.day;
  let season = Kingdom.season;
  let weather = Kingdom.weather;
  let events = Kingdom.events;
  let running = Kingdom.running;
  document.getElementById("chr-header").innerHTML = season_icon(season) + " " + season + " &nbsp;·&nbsp; " + weather_icon(weather) + " " + weather;
  document.getElementById("chr-day").textContent = "Day " + day;
  document.getElementById("chr-log").innerHTML = events.map(e => "<div class=\"chr-entry\">" + e + "</div>").join("");
  document.getElementById("chr-status").textContent = running ? "● RUNNING" : "○ PAUSED";
  return document.getElementById("chr-status").className = "chr-status " + (running ? "running" : "paused");
};

Kingdom.subscribe(() => {
  render();
});

