// Auto-generated by tools/embed_combat.js
window.COMBAT_SOURCES = {
  syn: `// ═══════════════════════════════════════════════════════════════════════════════
// Synth v1.0 — Combat Engine
//
// The logic IS the demo. All game rules are expressed as pure Synth functions.
// The DOM layer is thin — everything interesting happens in the language:
//
//   Constrained types enforce stat boundaries at function entry
//   Nested pattern matching resolves elemental affinities
//   @memo caches damage formulas — same inputs always produce the same hit
//   .field shorthand reads party state as data pipelines
//   String interpolation builds the combat log narratively
//   @pure/@effects draws the line between rules and randomness
// ═══════════════════════════════════════════════════════════════════════════════

// ── v0.2: Constrained types ───────────────────────────────────────────────────
// Violation throws at the boundary — stats outside range are impossible by type.

type HP        = int    where >= 0 && <= 200
type StatValue = int    where >= 1 && <= 20
type Level     = int    where >= 1 && <= 20
type HeroName  = string where length > 0
type ClassName = string where length > 0

// ── v0.1: Records ─────────────────────────────────────────────────────────────

record Hero {
  name: string
  heroClass: string
  hp: int
  maxHp: int
  strength: int
  defense: int
  level: int
  alive: bool
}

record Enemy {
  name: string
  hp: int
  maxHp: int
  attack: int
  defense: int
  weakness: string
  alive: bool
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.2: SHORT-FORM FUNCTIONS
// ══════════════════════════════════════════════════════════════════════════════

fn hero_is_alive(h) = h.alive
fn any_alive(party) = party |> any(.alive)

// v0.3: string interpolation — {ident} and {ident.prop} forms
fn format_attack_msg(attacker, outcome, defender, dmg) =
  "{attacker} {outcome} {defender} for {dmg} damage!"

fn format_death_msg(name) = "{name} has fallen in battle."

fn format_hero_label(hero) = "{hero.name} Lv.{hero.level} {hero.heroClass}"

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: STRING INTERPOLATION — local let bindings as interpolation targets
// ══════════════════════════════════════════════════════════════════════════════

// HP bar: "████░░░░ 45/80 (56%)" built entirely from pure Synth functions
fn hp_bar_text :: (hp: int, maxHp: int) -> string {
  @pure @total
  @intent "Generate a visual HP bar string with percentage"
  let filled = maxHp > 0 ? Math.max(0, Math.round(hp / maxHp * 8)) : 0
  let bar    = range(0, 8) |> map(i => i < filled ? "#" : ".") 
  let pct    = maxHp > 0 ? Math.floor(hp / maxHp * 100) : 0
  let barStr = bar.join("")
  "{barStr} {hp}/{maxHp} ({pct}%)"
}

fn format_hero_card_line :: (hero: Hero) -> string {
  @pure @total
  @intent "One-line hero status for the combat panel"
  let bar = hp_bar_text(hero.hp, hero.maxHp)
  let title = level_title(hero.level)
  "{hero.name} the {title}  {bar}"
}

fn format_enemy_card_line :: (enemy: Enemy) -> string {
  @pure @total
  @intent "One-line enemy status for the combat panel"
  let bar = hp_bar_text(enemy.hp, enemy.maxHp)
  "{enemy.name}  {bar}"
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.1: PATTERN MATCHING
// ══════════════════════════════════════════════════════════════════════════════

fn level_title :: (level: int) -> string {
  @pure @total
  @intent "Rank title based on level range"
  match level {
    | < 4  => "Novice"
    | < 7  => "Adept"
    | < 10 => "Veteran"
    | _    => "Master"
  }
}

fn combat_outcome_label :: (roll: int) -> string {
  @pure @total
  @intent "Narrative label for a d20 attack roll"
  match roll {
    | >= 20 => "lands a perfect strike on"
    | >= 18 => "scores a CRITICAL HIT on"
    | >= 8  => "hits"
    | >= 3  => "grazes"
    | _     => "misses"
  }
}

// Nested match: class vs weakness — only possible because match is an expression
fn element_bonus :: (heroClass: string, weakness: string) -> int {
  @pure @total
  @intent "Extra damage when class targets enemy weakness — nested match on two axes"
  match heroClass {
    | "mage"   => match weakness { | "arcane"   => 8 | "fire" => 5 | _ => 0 }
    | "ranger" => match weakness { | "nature"   => 6 | "cold" => 4 | _ => 0 }
    | "knight" => match weakness { | "physical" => 5 | _       => 0 }
    | _        => 0
  }
}

fn class_symbol :: (heroClass: string) -> string {
  @pure @total
  @intent "Single-char symbol for each hero class"
  match heroClass {
    | "mage"   => "[M]"
    | "knight" => "[K]"
    | "ranger" => "[R]"
    | _        => "[?]"
  }
}

fn class_weakness_hint :: (weakness: string) -> string {
  @pure @total
  @intent "Display label for enemy weakness"
  match weakness {
    | "arcane"   => "weak to ARCANE (mage bonus)"
    | "fire"     => "weak to FIRE (mage bonus)"
    | "nature"   => "weak to NATURE (ranger bonus)"
    | "cold"     => "weak to COLD (ranger bonus)"
    | "physical" => "weak to PHYSICAL (knight bonus)"
    | _          => "no known weakness"
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: @MEMO — compile-time memoization
//
// Damage calculation is deterministic given inputs. @memo ensures that if two
// heroes with the same stats attack the same enemy with the same roll, the
// result is cached and the formula runs only once ever.
// ══════════════════════════════════════════════════════════════════════════════

fn compute_damage :: (atk: int, def: int, bonus: int, roll: int) -> int {
  @pure @total @memo
  @intent "Core damage formula — memoized, same inputs always produce same damage"
  let base = Math.max(1, atk + bonus - Math.floor(def / 2))
  let mult = roll >= 18 ? 2 : 1
  Math.max(1, base * mult)
}

fn hero_power :: (hero: Hero) -> int {
  @pure @total @memo
  @intent "Composite strength rating — memoized per unique hero state"
  hero.strength * hero.level + Math.floor(hero.maxHp / 10)
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: PARAM VALIDATION INJECTION
//
// create_hero has 5 constrained-type params. The compiler injects 5 guard
// clauses at function entry — no manual validation code needed.
// ══════════════════════════════════════════════════════════════════════════════

fn create_hero :: (name: HeroName, heroClass: ClassName, hp: HP, strength: StatValue, defense: StatValue, level: Level) -> Hero {
  @pure @total
  @intent "Construct a Hero — all 5 typed params auto-validated at entry"
  { name, heroClass, hp, maxHp: hp, strength, defense, level, alive: true }
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: .FIELD ACCESSOR SHORTHAND
// ══════════════════════════════════════════════════════════════════════════════

fn alive_heroes :: (party: Hero[]) -> Hero[] {
  @pure @total
  @intent "Living party members via .alive shorthand"
  party |> filter(.alive)
}

fn party_names :: (party: Hero[]) -> string[] {
  @pure @total
  @intent "Names of all living heroes — chain of .field shorthands"
  party |> filter(.alive) |> map(.name)
}

fn total_party_hp :: (party: Hero[]) -> int {
  @pure @total @memo
  @intent "Sum of living HP — .hp shorthand after .alive filter"
  party |> filter(.alive) |> map(.hp) |> sum
}

fn party_power_rating :: (party: Hero[]) -> int {
  @pure @total @memo
  @intent "Sum of hero_power across all party members"
  party |> map(hero_power) |> sum
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.2: STDLIB SHOWCASE
// ══════════════════════════════════════════════════════════════════════════════

fn count_alive :: (party: Hero[]) -> int {
  @pure @total
  @intent "Count surviving heroes"
  party |> filter(.alive) |> count
}

fn strongest_hero :: (party: Hero[]) -> Hero {
  @pure @total
  @intent "The hero with the highest power rating"
  // v1.0: max_by replaces sort-then-first — no mutation, no checker warning
  party |> max_by(hero_power)
}

// Intentionally impure — demonstrates @pure checker warning
fn debug_party :: (party: Hero[]) -> bool {
  @pure @total
  @intent "Debug party state — @pure is false, checker will warn"
  let _ = console.log("debug_party:", party |> map(.name))
  true
}

// ══════════════════════════════════════════════════════════════════════════════
// PURE UTILITIES
// ══════════════════════════════════════════════════════════════════════════════

fn apply_damage :: (entity: any, dmg: int) -> any {
  @pure @total
  @intent "Return entity with updated hp and alive flag — no mutation"
  let newHp = Math.max(0, entity.hp - dmg)
  { ...entity, hp: newHp, alive: newHp > 0 }
}

// ══════════════════════════════════════════════════════════════════════════════
// DOM BUILDER
// ══════════════════════════════════════════════════════════════════════════════

fn el :: (tag: string, attrs: object, ...children: any[]) -> Element {
  @effects [dom.create, dom.attrs, dom.children]
  @intent "Create a DOM element with attributes and children"
  let e = document.createElement(tag)
  let _ = Object.entries(attrs).forEach(([k, v]) => {
    if (k === "class") { e.className = v }
    else if (k === "id") { e.id = v }
    else if (k === "disabled") { e.disabled = v }
    else if (k === "type") { e.type = v }
    else if (k.startsWith("on")) { e.addEventListener(k.slice(2).toLowerCase(), v) }
    else { e.setAttribute(k, String(v)) }
  })
  let _ = children.flat().forEach(child => {
    if (typeof child === "string") { e.appendChild(document.createTextNode(child)) }
    else if (child instanceof Node) { e.appendChild(child) }
  })
  e
}

// ══════════════════════════════════════════════════════════════════════════════
// RENDERERS — pure element builders
// ══════════════════════════════════════════════════════════════════════════════

fn render_hero_row :: (hero: Hero) -> Element {
  @effects [dom.create]
  @intent "Render one hero row with HP bar and stats"
  let sym   = class_symbol(hero.heroClass)
  let label = format_hero_card_line(hero)
  let power = hero_power(hero)
  let rowClass = hero.alive ? "hero-row" : "hero-row hero-dead"
  el("div", { class: rowClass },
    el("span", { class: "hero-sym" },  sym),
    el("span", { class: "hero-label"}, label),
    el("span", { class: "hero-pwr" },  \`PWR:\${power}\`)
  )
}

fn render_enemy_panel :: (enemy: Enemy) -> Element {
  @effects [dom.create]
  @intent "Render the enemy status panel"
  let label   = format_enemy_card_line(enemy)
  let hint    = class_weakness_hint(enemy.weakness)
  el("div", { class: "enemy-panel" },
    el("div", { class: "enemy-name" },    enemy.name),
    el("div", { class: "enemy-bar" },     label),
    el("div", { class: "enemy-hint" },    hint),
    el("div", { class: "enemy-stats" },   \`ATK:\${enemy.attack}  DEF:\${enemy.defense}\`)
  )
}

fn render_party_panel :: (party: Hero[]) -> Element {
  @effects [dom.create]
  @intent "Render all hero rows with party-level stats"
  let aliveCount  = count_alive(party)
  let totalHp     = total_party_hp(party)
  let powerRating = party_power_rating(party)
  let summaryStr  = "Party: {aliveCount} alive · {totalHp} HP · PWR {powerRating}"
  let rows = party |> map(render_hero_row)
  let container = el("div", { class: "party-panel" })
  let _ = rows.forEach(row => container.appendChild(row))
  let _ = container.appendChild(el("div", { class: "party-summary" }, summaryStr))
  container
}

// ══════════════════════════════════════════════════════════════════════════════
// MAIN ENTRY — orchestrates state, events, re-renders
// ══════════════════════════════════════════════════════════════════════════════

fn render_combat :: (rootId: string) -> void {
  @effects [dom.write, dom.events, state.mutable, rng]
  @intent "Bootstrap the combat engine — pure logic, thin DOM layer"

  let make_party = () => [
    create_hero("Aria",   "mage",   60, 12, 5,  8),
    create_hero("Theron", "knight", 80,  8, 12, 6),
    create_hero("Lyra",   "ranger", 70, 10,  7, 7)
  ]

  // v1.0: object literal directly in lambda body
  let make_enemy = () =>
    { name: "Shadow Drake", hp: 160, maxHp: 160, attack: 14, defense: 8, weakness: "arcane", alive: true }

  let party      = make_party()
  let enemy      = make_enemy()
  let log_lines  = []
  let round_num  = 0
  let over       = false

  let root = document.getElementById(rootId)
  let _ = root.innerHTML = ""

  let partyEl  = el("div", { class: "panel-party" })
  let enemyEl  = el("div", { class: "panel-enemy" })
  let battleEl = el("div", { class: "battle-panels" })
  let _ = battleEl.appendChild(partyEl)
  let _ = battleEl.appendChild(enemyEl)

  let logEl    = el("div", { class: "combat-log" })
  let attackBtn = el("button", { class: "btn-attack" }, "ATTACK")
  let resetBtn  = el("button", { class: "btn-reset" }, "NEW BATTLE")
  let btnRow    = el("div", { class: "btn-row" }, attackBtn, resetBtn)

  let _ = root.appendChild(battleEl)
  let _ = root.appendChild(logEl)
  let _ = root.appendChild(btnRow)

  let addLog = (msg) => {
    let _ = log_lines.push(msg)
    let entry = el("div", { class: "log-entry" }, msg)
    let _ = logEl.appendChild(entry)
    let _ = logEl.scrollTop = logEl.scrollHeight
  }

  let refresh = () => {
    partyEl.innerHTML = ""
    let _ = partyEl.appendChild(render_party_panel(party))
    enemyEl.innerHTML = ""
    let _ = enemyEl.appendChild(render_enemy_panel(enemy))
    attackBtn.disabled = over
  }

  let _ = attackBtn.addEventListener("click", () => {
    let alive = alive_heroes(party)
    if (alive.length > 0 && enemy.alive && !over) {
      round_num = round_num + 1
      addLog("── Round {round_num} ──")

      // Hero attacks — pure damage formula + effectful dice roll
      let hi      = Math.floor(Math.random() * alive.length)
      let hero    = alive[hi]
      let roll    = Math.floor(Math.random() * 20) + 1
      let bonus   = element_bonus(hero.heroClass, enemy.weakness)
      let dmg     = compute_damage(hero.strength, enemy.defense, bonus, roll)
      let outcome = combat_outcome_label(roll)
      let eName   = enemy.name
      enemy = apply_damage(enemy, dmg)
      addLog(format_attack_msg(hero.name, outcome, eName, dmg))
      if (bonus > 0) {
        addLog("  [elemental bonus: +{bonus} from {hero.heroClass} vs {enemy.weakness}]")
      }
      if (!enemy.alive) {
        addLog("** {eName} has been slain! VICTORY! **")
        over = true
      }

      // Enemy counterattacks
      if (enemy.alive) {
        let ti      = Math.floor(Math.random() * alive.length)
        let target  = alive[ti]
        let eDmg    = compute_damage(enemy.attack, target.defense, 0, 10)
        let dies    = target.hp - eDmg <= 0
        party = party |> map(h => h.name === target.name ? apply_damage(h, eDmg) : h)
        addLog(format_attack_msg(eName, "strikes back at", target.name, eDmg))
        if (dies) {
          addLog(format_death_msg(target.name))
        }
        if (alive_heroes(party).length === 0) {
          addLog("** Your party has been defeated. GAME OVER. **")
          over = true
        }
      }

      refresh()
    }
  })

  let _ = resetBtn.addEventListener("click", () => {
    party     = make_party()
    enemy     = make_enemy()
    log_lines = []
    round_num = 0
    over      = false
    logEl.innerHTML = ""
    addLog("A new battle begins.")
    addLog("Shadow Drake emerges from the darkness — {enemy.weakness}.")
    refresh()
  })

  // Initial log
  addLog("SYNTH COMBAT ENGINE — pure rules, memoized formulas, type-safe stats")
  addLog("Shadow Drake appears — {enemy.weakness}.")
  addLog("Aria (mage) has arcane bonus vs this enemy.")
  addLog("Press ATTACK to begin.")
  refresh()
}
`,
  js:  `
const Hero = (name, heroClass, hp, maxHp, strength, defense, level, alive) => ({ name, heroClass, hp, maxHp, strength, defense, level, alive });

const Enemy = (name, hp, maxHp, attack, defense, weakness, alive) => ({ name, hp, maxHp, attack, defense, weakness, alive });

const hero_is_alive = (h) => h.alive;

const any_alive = (party) => \$any(party, (__x) => __x.alive);

const format_attack_msg = (attacker, outcome, defender, dmg) => \`\${attacker} \${outcome} \${defender} for \${dmg} damage!\`;

const format_death_msg = (name) => \`\${name} has fallen in battle.\`;

const format_hero_label = (hero) => \`\${hero.name} Lv.\${hero.level} \${hero.heroClass}\`;

/**
 * @param {number} hp
 * @param {number} maxHp
 * @returns {string}
 */
const hp_bar_text = (hp, maxHp) => {
  let filled = maxHp > 0 ? Math.max(0, Math.round(hp / maxHp * 8)) : 0;
  let bar = \$map(\$range(0, 8), (i) => i < filled ? "#" : ".");
  let pct = maxHp > 0 ? Math.floor(hp / maxHp * 100) : 0;
  let barStr = bar.join("");
  return \`\${barStr} \${hp}/\${maxHp} (\${pct}%)\`;
};

/**
 * @param {Hero} hero
 * @returns {string}
 */
const format_hero_card_line = (hero) => {
  let bar = hp_bar_text(hero.hp, hero.maxHp);
  let title = level_title(hero.level);
  return \`\${hero.name} the \${title}  \${bar}\`;
};

/**
 * @param {Enemy} enemy
 * @returns {string}
 */
const format_enemy_card_line = (enemy) => {
  let bar = hp_bar_text(enemy.hp, enemy.maxHp);
  return \`\${enemy.name}  \${bar}\`;
};

/**
 * @param {number} level
 * @returns {string}
 */
const level_title = (level) => ((_m) => (_m < 4) ? "Novice" : (_m < "7") ? "Adept" : (_m < "10") ? "Veteran" : "Master")(level);

/**
 * @param {number} roll
 * @returns {string}
 */
const combat_outcome_label = (roll) => ((_m) => (_m >= "20") ? "lands a perfect strike on" : (_m >= "18") ? "scores a CRITICAL HIT on" : (_m >= "8") ? "hits" : (_m >= 3) ? "grazes" : "misses")(roll);

/**
 * @param {string} heroClass
 * @param {string} weakness
 * @returns {number}
 */
const element_bonus = (heroClass, weakness) => ((_m) => (_m === "mage") ? ((_m) => (_m === "arcane") ? 8 : (_m === "fire") ? 5 : 0)(weakness) : (_m === "ranger") ? ((_m) => (_m === "nature") ? 6 : (_m === "cold") ? 4 : 0)(weakness) : (_m === "knight") ? ((_m) => (_m === "physical") ? 5 : 0)(weakness) : 0)(heroClass);

/**
 * @param {string} heroClass
 * @returns {string}
 */
const class_symbol = (heroClass) => ((_m) => (_m === "mage") ? "[M]" : (_m === "knight") ? "[K]" : (_m === "ranger") ? "[R]" : "[?]")(heroClass);

/**
 * @param {string} weakness
 * @returns {string}
 */
const class_weakness_hint = (weakness) => ((_m) => (_m === "arcane") ? "weak to ARCANE (mage bonus)" : (_m === "fire") ? "weak to FIRE (mage bonus)" : (_m === "nature") ? "weak to NATURE (ranger bonus)" : (_m === "cold") ? "weak to COLD (ranger bonus)" : (_m === "physical") ? "weak to PHYSICAL (knight bonus)" : "no known weakness")(weakness);

const compute_damage = (() => {
  const __cache = new Map();
  return (atk, def, bonus, roll) => {
    const __key = JSON.stringify([atk, def, bonus, roll]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      let base = Math.max(1, atk + bonus - Math.floor(def / 2));
      let mult = roll >= 18 ? 2 : 1;
      return Math.max(1, base * mult);
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

const hero_power = (() => {
  const __cache = new Map();
  return (hero) => {
    const __key = JSON.stringify([hero]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return hero.strength * hero.level + Math.floor(hero.maxHp / 10);
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * @param {HeroName} name
 * @param {ClassName} heroClass
 * @param {HP} hp
 * @param {StatValue} strength
 * @param {StatValue} defense
 * @param {Level} level
 * @returns {Hero}
 */
const create_hero = (name, heroClass, hp, strength, defense, level) => ({name: name, heroClass: heroClass, hp: hp, maxHp: hp, strength: strength, defense: defense, level: level, alive: true});

/**
 * @param {Hero} party
 * @returns {Hero}
 */
const alive_heroes = (party) => \$filter(party, (__x) => __x.alive);

/**
 * @param {Hero} party
 * @returns {string}
 */
const party_names = (party) => \$map(\$filter(party, (__x) => __x.alive), (__x) => __x.name);

const total_party_hp = (() => {
  const __cache = new Map();
  return (party) => {
    const __key = JSON.stringify([party]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return \$sum(\$map(\$filter(party, (__x) => __x.alive), (__x) => __x.hp));
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

const party_power_rating = (() => {
  const __cache = new Map();
  return (party) => {
    const __key = JSON.stringify([party]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return \$sum(\$map(party, hero_power));
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * @param {Hero} party
 * @returns {number}
 */
const count_alive = (party) => \$count(\$filter(party, (__x) => __x.alive));

/**
 * @param {Hero} party
 * @returns {Hero}
 */
const strongest_hero = (party) => \$max_by(party, hero_power);

/**
 * @param {Hero} party
 * @returns {boolean}
 */
const debug_party = (party) => {
  console.log("debug_party:", \$map(party, (__x) => __x.name));
  return true;
};

/**
 * @param {*} entity
 * @param {number} dmg
 * @returns {*}
 */
const apply_damage = (entity, dmg) => {
  let newHp = Math.max(0, entity.hp - dmg);
  return {_spread_: entity, hp: newHp, alive: newHp > 0};
};

/**
 * @param {string} tag
 * @param {object} attrs
 * @param {*} ...children
 * @returns {Element}
 */
const el = (tag, attrs, ...children) => {
  let e = document.createElement(tag);
  Object.entries(attrs).forEach(([k, v]) => (() => {
    if (k === "class") {
      return e.className = v;
    } else if (k === "id") {
      return e.id = v;
    } else if (k === "disabled") {
      return e.disabled = v;
    } else if (k === "type") {
      return e.type = v;
    } else if (k.startsWith("on")) {
      return e.addEventListener(k.slice(2).toLowerCase(), v);
    } else {
      return e.setAttribute(k, String(v));
    }
})());
  \$flat(children, ).forEach((child) => (() => {
    if (typeof child === "string") {
      return e.appendChild(document.createTextNode(child));
    } else if (child instanceof Node) {
      return e.appendChild(child);
    }
})());
  return e;
};

/**
 * @param {Hero} hero
 * @returns {Element}
 */
const render_hero_row = (hero) => {
  let sym = class_symbol(hero.heroClass);
  let label = format_hero_card_line(hero);
  let power = hero_power(hero);
  let rowClass = hero.alive ? "hero-row" : "hero-row hero-dead";
  return el("div", {class: rowClass}, el("span", {class: "hero-sym"}, sym), el("span", {class: "hero-label"}, label), el("span", {class: "hero-pwr"}, \`PWR:\${power}\`));
};

/**
 * @param {Enemy} enemy
 * @returns {Element}
 */
const render_enemy_panel = (enemy) => {
  let label = format_enemy_card_line(enemy);
  let hint = class_weakness_hint(enemy.weakness);
  return el("div", {class: "enemy-panel"}, el("div", {class: "enemy-name"}, enemy.name), el("div", {class: "enemy-bar"}, label), el("div", {class: "enemy-hint"}, hint), el("div", {class: "enemy-stats"}, \`ATK:\${enemy.attack}  DEF:\${enemy.defense}\`));
};

/**
 * @param {Hero} party
 * @returns {Element}
 */
const render_party_panel = (party) => {
  let aliveCount = count_alive(party);
  let totalHp = total_party_hp(party);
  let powerRating = party_power_rating(party);
  let summaryStr = \`Party: \${aliveCount} alive · \${totalHp} HP · PWR \${powerRating}\`;
  let rows = \$map(party, render_hero_row);
  let container = el("div", {class: "party-panel"});
  rows.forEach((row) => container.appendChild(row));
  container.appendChild(el("div", {class: "party-summary"}, summaryStr));
  return container;
};

/**
 * @param {string} rootId
 * @returns {void}
 */
const render_combat = (rootId) => {
  let make_party = () => [create_hero("Aria", "mage", 60, 12, 5, 8), create_hero("Theron", "knight", 80, 8, 12, 6), create_hero("Lyra", "ranger", 70, 10, 7, 7)];
  let make_enemy = () => ({name: "Shadow Drake", hp: 160, maxHp: 160, attack: 14, defense: 8, weakness: "arcane", alive: true});
  let party = make_party();
  let enemy = make_enemy();
  let log_lines = [];
  let round_num = 0;
  let over = false;
  let root = document.getElementById(rootId);
  root.innerHTML = "";
  let partyEl = el("div", {class: "panel-party"});
  let enemyEl = el("div", {class: "panel-enemy"});
  let battleEl = el("div", {class: "battle-panels"});
  battleEl.appendChild(partyEl);
  battleEl.appendChild(enemyEl);
  let logEl = el("div", {class: "combat-log"});
  let attackBtn = el("button", {class: "btn-attack"}, "ATTACK");
  let resetBtn = el("button", {class: "btn-reset"}, "NEW BATTLE");
  let btnRow = el("div", {class: "btn-row"}, attackBtn, resetBtn);
  root.appendChild(battleEl);
  root.appendChild(logEl);
  root.appendChild(btnRow);
  let addLog = (msg) => (() => {
    log_lines.push(msg);
    let entry = el("div", {class: "log-entry"}, msg);
    logEl.appendChild(entry);
    logEl.scrollTop = logEl.scrollHeight;
})();
  let refresh = () => (() => {
    partyEl.innerHTML = "";
    partyEl.appendChild(render_party_panel(party));
    enemyEl.innerHTML = "";
    enemyEl.appendChild(render_enemy_panel(enemy));
    return attackBtn.disabled = over;
})();
  attackBtn.addEventListener("click", () => (() => {
    let alive = alive_heroes(party);
    if (alive.length > 0 && enemy.alive && !over) {
      round_num = round_num + 1;
      addLog(\`── Round \${round_num} ──\`);
      let hi = Math.floor(Math.random() * alive.length);
      let hero = alive[hi];
      let roll = Math.floor(Math.random() * 20) + 1;
      let bonus = element_bonus(hero.heroClass, enemy.weakness);
      let dmg = compute_damage(hero.strength, enemy.defense, bonus, roll);
      let outcome = combat_outcome_label(roll);
      let eName = enemy.name;
      enemy = apply_damage(enemy, dmg);
      addLog(format_attack_msg(hero.name, outcome, eName, dmg));
      if (bonus > 0) {
        addLog(\`  [elemental bonus: +\${bonus} from \${hero.heroClass} vs \${enemy.weakness}]\`);
      }
      if (!enemy.alive) {
        addLog(\`** \${eName} has been slain! VICTORY! **\`);
        over = true;
      }
      if (enemy.alive) {
        let ti = Math.floor(Math.random() * alive.length);
        let target = alive[ti];
        let eDmg = compute_damage(enemy.attack, target.defense, 0, 10);
        let dies = target.hp - eDmg <= 0;
        party = \$map(party, (h) => h.name === target.name ? apply_damage(h, eDmg) : h);
        addLog(format_attack_msg(eName, "strikes back at", target.name, eDmg));
        if (dies) {
          addLog(format_death_msg(target.name));
        }
        if (alive_heroes(party).length === 0) {
          addLog("** Your party has been defeated. GAME OVER. **");
          over = true;
        }
      }
      return refresh();
    }
})());
  resetBtn.addEventListener("click", () => (() => {
    party = make_party();
    enemy = make_enemy();
    log_lines = [];
    round_num = 0;
    over = false;
    logEl.innerHTML = "";
    addLog("A new battle begins.");
    addLog(\`Shadow Drake emerges from the darkness — \${enemy.weakness}.\`);
    return refresh();
})());
  addLog("SYNTH COMBAT ENGINE — pure rules, memoized formulas, type-safe stats");
  addLog(\`Shadow Drake appears — \${enemy.weakness}.\`);
  addLog("Aria (mage) has arcane bonus vs this enemy.");
  addLog("Press ATTACK to begin.");
  return refresh();
};

`,
};
