// ─── tiles.axn ─────────────────────────────────────────
// Generated by Axon v0.5.2 transpiler
// DO NOT EDIT — source: .axn


// ── Axon v0.4.0 stdlib ──────────────────────────────────────────────────────

/**
 * Apply fn to every element of xs and return the results.
 * @pure @total
 * @param {Array} xs
 * @param {Function} fn
 * @returns {Array}
 */
const map = (xs, fn) => xs.map(fn);

/**
 * Keep only elements of xs for which pred returns true.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {Array}
 */
const filter = (xs, pred) => xs.filter(pred);

/**
 * Reduce xs to a single value, starting from init.
 * @pure @total
 * @param {Array} xs
 * @param {*} init
 * @param {Function} fn
 * @returns {*}
 */
const fold = (xs, init, fn) => xs.reduce(fn, init);

/**
 * Apply a sequence of single-argument functions left to right.
 * @pure @total
 * @param {...Function} fns
 * @returns {Function}
 */
const pipe = (...fns) => (x) => fns.reduce((v, f) => f(v), x);

/**
 * Combine two arrays element-by-element into pairs.
 * @pure @total
 * @param {Array} xs
 * @param {Array} ys
 * @returns {Array}
 */
const zip = (xs, ys) => xs.map((x, i) => [x, ys[i]]);

/**
 * Produce an array of integers from start (inclusive) to end (exclusive).
 * @pure @total
 * @param {number} start
 * @param {number} end
 * @returns {number[]}
 */
const range = (start, end) => Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);

/**
 * Return the first element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const first = (xs) => xs[0];

/**
 * Return the last element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const last = (xs) => xs[xs.length - 1];

/**
 * Sum a numeric array.
 * @pure @total
 * @param {number[]} xs
 * @returns {number}
 */
const sum = (xs) => xs.reduce((a, b) => a + b, 0);

/**
 * Count elements matching pred, or total length if no pred given.
 * @pure @total
 * @param {Array} xs
 * @param {Function} [pred]
 * @returns {number}
 */
const count = (xs, pred) => pred ? xs.filter(pred).length : xs.length;

/**
 * True if any element satisfies pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const any = (xs, pred) => xs.some(pred);

/**
 * True if all elements satisfy pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const all = (xs, pred) => xs.every(pred);

/**
 * Flatten one level of nesting.
 * @pure @total
 * @param {Array} xs
 * @returns {Array}
 */
const flat = (xs) => xs.flat();

/**
 * Group an array into a Map by key function.
 * @pure @total
 * @param {Array} xs
 * @param {Function} keyFn
 * @returns {Map}
 */
const groupBy = (xs, keyFn) => xs.reduce((m, x) => {
  const k = keyFn(x);
  if (!m.has(k)) m.set(k, []);
  m.get(k).push(x);
  return m;
}, new Map());

/**
 * Return a new object with only the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const pick = (obj, keys) => Object.fromEntries(keys.filter(k => k in obj).map(k => [k, obj[k]]));

/**
 * Return a new object without the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const omit = (obj, keys) => Object.fromEntries(Object.entries(obj).filter(([k]) => !keys.includes(k)));

// ── Axon built-in constraint validators ─────────────────────────────────────
// Generated by 'type T = base where ...' declarations.

const __axon_presets = {
  email:   /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  url:     /^https?:\/\//,
  uuid:    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  alpha:   /^[a-zA-Z]+$/,
  alnum:   /^[a-zA-Z0-9]+$/,
  numeric: /^[0-9]+$/,
  slug:    /^[a-z0-9-]+$/,
  hex:     /^#?[0-9a-fA-F]{3,8}$/,
};

// ── Axon v0.4.0 test runner ──────────────────────────────────────────────────
// @test declarations push entries here. Call __runAxonTests() to execute them.
// Also exposed on globalThis so the CLI's vm context can access it.

const __axon_tests = [];

/**
 * Run all registered @test declarations. Returns a result summary.
 * @returns {{ passed: number, failed: number, total: number, results: Array }}
 */
const __runAxonTests = () => {
  let passed = 0, failed = 0;
  const results = [];
  for (const t of __axon_tests) {
    try {
      const ok = !!t.fn();
      if (ok) {
        passed++;
        results.push({ ok: true,  desc: t.desc });
      } else {
        failed++;
        results.push({ ok: false, desc: t.desc, error: 'assertion returned false' });
      }
    } catch(e) {
      failed++;
      results.push({ ok: false, desc: t.desc, error: String(e) });
    }
  }
  return { passed, failed, total: passed + failed, results };
};
// Expose on globalThis so the Node CLI vm context and browser window can both access it
if (typeof globalThis !== 'undefined') {
  globalThis.__axon_tests = __axon_tests;
  globalThis.__runAxonTests = __runAxonTests;
}

// Tagged union: Tile
const Floor = Object.freeze({ tag: "Floor" });
const Wall = Object.freeze({ tag: "Wall" });
const Door = Object.freeze({ tag: "Door" });
const Stairs = Object.freeze({ tag: "Stairs" });
const Chest = Object.freeze({ tag: "Chest" });
const Water = Object.freeze({ tag: "Water" });
const Torch = Object.freeze({ tag: "Torch" });

const is_passable = (tag) => tag == "Floor" || tag == "Door" || tag == "Stairs" || tag == "Torch";

const tile_glyph = (tag) => ((_m) => (_m === "Floor") ? "·" : (_m === "Wall") ? "█" : (_m === "Door") ? "▯" : (_m === "Stairs") ? "≋" : (_m === "Chest") ? "■" : (_m === "Water") ? "≈" : (_m === "Torch") ? "†" : "?")(tag);

const tile_label = (tag) => ((_m) => (_m === "Floor") ? "open floor" : (_m === "Wall") ? "stone wall" : (_m === "Door") ? "wooden door" : (_m === "Stairs") ? "staircase" : (_m === "Chest") ? "treasure chest" : (_m === "Water") ? "deep water" : (_m === "Torch") ? "wall torch" : "unknown")(tag);

__axon_tests.push({ desc: "floor is passable", fn: () => is_passable("Floor") == true });

__axon_tests.push({ desc: "wall is not passable", fn: () => is_passable("Wall") == false });

__axon_tests.push({ desc: "chest is not passable", fn: () => is_passable("Chest") == false });

__axon_tests.push({ desc: "stairs glyph is correct", fn: () => tile_glyph("Stairs") == "≋" });

__axon_tests.push({ desc: "door label is correct", fn: () => tile_label("Door") == "wooden door" });


// ─── generator.axn ─────────────────────────────────────
// Generated by Axon v0.5.2 transpiler
// DO NOT EDIT — source: .axn


/** @typedef {{
 *   grid: string,
 *   rows: number,
 *   cols: number,
 *   level: number
 * }} DungeonMap
 */

const lcg = (s) => (s % 2147483648 * 1664525 + 1013904223) % 2147483648;

/**
 * @param {number} s
 * @param {number} r
 * @param {number} c
 * @returns {number}
 */
const cell_hash = (s, r, c) => {
  let h1 = lcg(s + r * 48271 + c * 16807);
  let h2 = lcg(h1 + c * 48271 + r * 16807);
  let h3 = lcg(h2);
  return h3 / 2147483648;
};

/**
 * @param {number} rows
 * @param {number} cols
 * @returns {*}
 */
const make_grid = (rows, cols) => {
  let data = [];
  for (let _ = 0; _ < rows * cols; _++) {
    data.push("Wall");
  }
  return { data: data, cols: cols };
};

const gget = (g, r, c) => g.data[r * g.cols + c];

/**
 * @param {*} g
 * @param {number} r
 * @param {number} c
 * @param {string} tag
 * @returns {*}
 */
const gset = (g, r, c, tag) => g.data[r * g.cols + c] = tag;

const room_cr = (room) => room.r1 + Math.floor((room.r2 - room.r1) / 2);

const room_cc = (room) => room.c1 + Math.floor((room.c2 - room.c1) / 2);

/**
 * @param {number} rows
 * @param {number} cols
 * @param {number} s
 * @returns {*}
 */
const pick_room = (rows, cols, s) => {
  let s1 = lcg(s);
  let maxh = Math.max(2, Math.floor(rows / 3));
  let maxw = Math.max(3, Math.floor(cols / 4));
  let h = 2 + s1 % maxh;
  let s2 = lcg(s1);
  let w = 3 + s2 % maxw;
  let s3 = lcg(s2);
  let r1 = 1 + s3 % Math.max(1, rows - h - 2);
  let s4 = lcg(s3);
  let c1 = 1 + s4 % Math.max(1, cols - w - 2);
  return { r1: r1, c1: c1, r2: r1 + h, c2: c1 + w };
};

/**
 * @param {*} g
 * @param {*} room
 * @returns {*}
 */
const carve_room = (g, room) => {
  for (let i = 0; i < room.r2 - room.r1 + 1; i++) {
    for (let j = 0; j < room.c2 - room.c1 + 1; j++) {
      gset(g, room.r1 + i, room.c1 + j, "Floor");
    }
  }
};

/**
 * @param {*} g
 * @param {number} r
 * @param {number} clo
 * @param {number} chi
 * @returns {*}
 */
const carve_h = (g, r, clo, chi) => {
  for (let c = clo; c <= chi; c++) {
    if (gget(g, r, c) == "Wall") {
      gset(g, r, c, "Floor");
    }
  }
};

/**
 * @param {*} g
 * @param {number} c
 * @param {number} rlo
 * @param {number} rhi
 * @returns {*}
 */
const carve_v = (g, c, rlo, rhi) => {
  for (let r = rlo; r <= rhi; r++) {
    if (gget(g, r, c) == "Wall") {
      gset(g, r, c, "Floor");
    }
  }
};

/**
 * @param {*} g
 * @param {number} r1
 * @param {number} c1
 * @param {number} r2
 * @param {number} c2
 * @returns {*}
 */
const carve_corridor = (g, r1, c1, r2, c2) => {
  carve_h(g, r1, Math.min(c1, c2), Math.max(c1, c2));
  return carve_v(g, c2, Math.min(r1, r2), Math.max(r1, r2));
};

/**
 * @param {*} g
 * @param {*} room
 * @returns {*}
 */
const place_room_doors = (g, room) => {
  let dr = room.r2 - room.r1 + 1;
  let dc = room.c2 - room.c1 + 1;
  let ri = -1;
  for (let i = 0; i < dr; i++) {
    if (ri < 0 && gget(g, room.r1 + i, room.c2 + 1) == "Floor") {
      ri = i;
    }
  }
  if (ri >= 0) {
    let r = room.r1 + ri;
    let c = room.c2 + 1;
    if (gget(g, r - 1, c) == "Wall" && gget(g, r + 1, c) == "Wall") {
      return gset(g, r, c, "Door");
    }
  }
  let li = -1;
  for (let i = 0; i < dr; i++) {
    if (li < 0 && gget(g, room.r1 + i, room.c1 - 1) == "Floor") {
      li = i;
    }
  }
  if (li >= 0) {
    let r = room.r1 + li;
    let c = room.c1 - 1;
    if (gget(g, r - 1, c) == "Wall" && gget(g, r + 1, c) == "Wall") {
      return gset(g, r, c, "Door");
    }
  }
  let bi = -1;
  for (let j = 0; j < dc; j++) {
    if (bi < 0 && gget(g, room.r2 + 1, room.c1 + j) == "Floor") {
      bi = j;
    }
  }
  if (bi >= 0) {
    let r = room.r2 + 1;
    let c = room.c1 + bi;
    if (gget(g, r, c - 1) == "Wall" && gget(g, r, c + 1) == "Wall") {
      return gset(g, r, c, "Door");
    }
  }
  let ti = -1;
  for (let j = 0; j < dc; j++) {
    if (ti < 0 && gget(g, room.r1 - 1, room.c1 + j) == "Floor") {
      ti = j;
    }
  }
  if (ti >= 0) {
    let r = room.r1 - 1;
    let c = room.c1 + ti;
    if (gget(g, r, c - 1) == "Wall" && gget(g, r, c + 1) == "Wall") {
      return gset(g, r, c, "Door");
    }
  }
};

/**
 * @param {*} g
 * @param {*} room
 * @param {number} level
 * @param {number} seed
 * @param {boolean} is_last
 * @returns {*}
 */
const scatter_room = (g, room, level, seed, is_last) => {
  if (is_last) {
    return gset(g, room_cr(room), room_cc(room), "Stairs");
  }
  let dr = room.r2 - room.r1 + 1;
  let dc = room.c2 - room.c1 + 1;
  let cp = 0.025;
  let wp = 0.02;
  for (let i = 0; i < dr; i++) {
    for (let j = 0; j < dc; j++) {
      let r = room.r1 + i;
      let c = room.c1 + j;
      let rng = cell_hash(seed, r, c);
      if (gget(g, r, c) == "Floor") {
        if (rng < cp) {
          gset(g, r, c, "Chest");
        }
        if (rng >= cp && rng < cp + wp) {
          gset(g, r, c, "Water");
        }
      }
    }
  }
};

/**
 * @param {*} g
 * @param {*} rooms
 * @returns {*}
 */
const fix_chest_count = (g, rooms) => {
  let positions = [];
  for (const room of rooms) {
    let dr = room.r2 - room.r1 + 1;
    let dc = room.c2 - room.c1 + 1;
    for (let i = 0; i < dr; i++) {
      for (let j = 0; j < dc; j++) {
        let r = room.r1 + i;
        let c = room.c1 + j;
        if (gget(g, r, c) == "Chest") {
          positions.push({ r: r, c: c });
        }
      }
    }
  }
  let idx = 0;
  for (const pos of positions) {
    if (idx >= 5) {
      gset(g, pos.r, pos.c, "Floor");
    }
    idx = idx + 1;
  }
  let count = Math.min(positions.length, 5);
  let ri = 0;
  for (const room of rooms) {
    if (count < 2 && ri < rooms.length - 1) {
      let r = room_cr(room);
      let c = room_cc(room);
      if (gget(g, r, c) == "Floor") {
        gset(g, r, c, "Chest");
        count = count + 1;
      }
    }
    ri = ri + 1;
  }
};

/**
 * @param {*} g
 * @param {number} rows
 * @param {number} cols
 * @returns {*}
 */
const place_door_torches = (g, rows, cols) => {
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      if (gget(g, r, c) == "Door") {
        if (r > 0 && c > 0 && gget(g, r - 1, c - 1) == "Floor") {
          gset(g, r - 1, c - 1, "Torch");
        }
        if (r > 0 && c < cols - 1 && gget(g, r - 1, c + 1) == "Floor") {
          gset(g, r - 1, c + 1, "Torch");
        }
        if (r < rows - 1 && c > 0 && gget(g, r + 1, c - 1) == "Floor") {
          gset(g, r + 1, c - 1, "Torch");
        }
        if (r < rows - 1 && c < cols - 1 && gget(g, r + 1, c + 1) == "Floor") {
          gset(g, r + 1, c + 1, "Torch");
        }
      }
    }
  }
};

/**
 * @param {number} rows
 * @param {number} cols
 * @param {number} level
 * @param {number} seed
 * @returns {DungeonMap}
 */
const generate = (rows, cols, level, seed) => {
  let g = make_grid(rows, cols);
  let rooms = [];
  let n = 4 + lcg(seed) % 4;
  for (let i = 0; i < n; i++) {
    let room = pick_room(rows, cols, lcg(seed + i * 997 + level * 113));
    rooms.push(room);
    carve_room(g, room);
  }
  for (let i = 0; i < n - 1; i++) {
    carve_corridor(g, room_cr(rooms[i]), room_cc(rooms[i]), room_cr(rooms[i + 1]), room_cc(rooms[i + 1]));
  }
  for (const room of rooms) {
    place_room_doors(g, room);
  }
  let si = 0;
  for (const room of rooms) {
    scatter_room(g, room, level, lcg(seed + si * 1009), si == n - 1);
    si = si + 1;
  }
  fix_chest_count(g, rooms);
  place_door_torches(g, rows, cols);
  let grid = [];
  for (let r = 0; r < rows; r++) {
    let row = [];
    for (let c = 0; c < cols; c++) {
      let tag = gget(g, r, c);
      let passable = tag != "Wall" && tag != "Chest" && tag != "Water";
      row.push({ tag: tag, passable: passable });
    }
    grid.push(row);
  }
  return { grid: JSON.stringify(grid), rows: rows, cols: cols, level: level };
};

/**
 * @param {DungeonMap} map
 * @param {string} tag
 * @returns {number}
 */
const count_tag = (map, tag) => {
  let grid = JSON.parse(map.grid);
  let count = 0;
  for (const row of grid) {
    for (const cell of row) {
      if (cell.tag == tag) {
        count = count + 1;
      }
    }
  }
  return count;
};

__axon_tests.push({ desc: "map has expected dimensions", fn: () => (() => {
  let m = generate(10, 20, 1, 42);
  return m.rows == 10 && m.cols == 20;
})() });

__axon_tests.push({ desc: "level-1 map has at least one floor tile", fn: () => (() => {
  let m = generate(10, 20, 1, 42);
  return count_tag(m, "Floor") > 0;
})() });

__axon_tests.push({ desc: "outer border is all wall", fn: () => (() => {
  let m = generate(8, 12, 1, 99);
  let g = JSON.parse(m.grid);
  return g[0].every(t => t.tag == "Wall") && g[7].every(t => t.tag == "Wall");
})() });

__axon_tests.push({ desc: "stairs present in every map", fn: () => (() => {
  let m = generate(10, 14, 1, 12);
  return count_tag(m, "Stairs") > 0;
})() });

__axon_tests.push({ desc: "chest count is between 2 and 5", fn: () => (() => {
  let m = generate(22, 48, 1, 7777);
  let m2 = generate(22, 48, 10, 9999);
  let c1 = count_tag(m, "Chest");
  let c2 = count_tag(m2, "Chest");
  return c1 >= 2 && c1 <= 5 && c2 >= 2 && c2 <= 5;
})() });

__axon_tests.push({ desc: "every torch is diagonally adjacent to a door", fn: () => (() => {
  let m = generate(22, 48, 1, 7777);
  let grid = JSON.parse(m.grid);
  let bad = 0;
  for (let r = 0; r < grid.length; r++) {
    for (let c = 0; c < grid[r].length; c++) {
      if (grid[r][c].tag == "Torch") {
        let diags = [[-1, -1], [-1, 1], [1, -1], [1, 1]];
        let hasDoor = diags.some((d) => {
          let nr = r + d[0];
          let nc = c + d[1];
          return nr >= 0 && nc >= 0 && nr < grid.length && nc < grid[r].length && grid[nr][nc].tag == "Door";
});
        if (!hasDoor) {
          bad = bad + 1;
        }
      }
    }
  }
  return bad == 0;
})() });


// ─── renderer.axn ──────────────────────────────────────
// Generated by Axon v0.5.2 transpiler
// DO NOT EDIT — source: .axn



const tile_class = (tag) => ((_m) => (_m === "Wall") ? "t-wall" : (_m === "Floor") ? "t-floor" : (_m === "Door") ? "t-door" : (_m === "Stairs") ? "t-stairs" : (_m === "Chest") ? "t-chest" : (_m === "Water") ? "t-water" : (_m === "Torch") ? "t-torch" : "t-unknown")(tag);

/**
 * @param {DungeonMap} map
 * @returns {string}
 */
const render_map = (map) => {
  let grid = JSON.parse(map.grid);
  let lines = [];
  grid.forEach((row) => {
    let cells = "";
    row.forEach((tile) => {
      let cls = tile_class(tile.tag);
      let glyph = tile_glyph(tile.tag);
      return cells = cells + "<span class=\"tile " + cls + "\">" + glyph + "</span>";
});
    return lines.push("<div class=\"map-row\">" + cells + "</div>");
});
  return "<div class=\"dungeon-map\">" + lines.join("") + "</div>";
};

/**
 * @param {string} tag
 * @returns {string}
 */
const legend_entry = (tag) => {
  let cls = tile_class(tag);
  let glyph = tile_glyph(tag);
  return "<div class=\"legend-entry\"><span class=\"tile " + cls + "\">" + glyph + "</span><span class=\"legend-label\">" + tag + "</span></div>";
};

/**
 * @returns {string}
 */
const render_legend = () => {
  let tags = ["Floor", "Wall", "Door", "Stairs", "Chest", "Water", "Torch"];
  let entries = tags.map(t => legend_entry(t));
  return "<div class=\"map-legend\">" + entries.join("") + "</div>";
};

/**
 * @param {DungeonMap} map
 * @param {number} seed
 * @returns {string}
 */
const render_stats = (map, seed) => {
  let grid = JSON.parse(map.grid);
  let floors = 0;
  let specials = 0;
  grid.forEach(row => row.forEach((cell) => {
    if (cell.tag == "Floor") {
      return floors = floors + 1;
    }
    if (cell.tag != "Floor" && cell.tag != "Wall") {
      return specials = specials + 1;
    }
}));
  return "<div class=\"map-stats\">" + "<span>Level <strong>" + map.level + "</strong></span>" + "<span>Seed <strong>" + seed + "</strong></span>" + "<span>Size <strong>" + map.cols + "×" + map.rows + "</strong></span>" + "<span>Floors <strong>" + floors + "</strong></span>" + "<span>Special <strong>" + specials + "</strong></span>" + "</div>";
};


// ─── main.axn ──────────────────────────────────────────
// Generated by Axon v0.5.2 transpiler
// DO NOT EDIT — source: .axn




/** @typedef {{
 *   level: number,
 *   seed: number,
 *   rows: number,
 *   cols: number
 * }} AppState
 */

/**
 * @returns {AppState}
 */
const init = () => ({ level: 1, seed: 7777, rows: 22, cols: 48 });

const next_seed = (s) => (s * 6364136 + 1442695) % 9007199254740991;

/**
 * @param {AppState} s
 * @returns {AppState}
 */
const new_map = (s) => ({ level: s.level, seed: next_seed(s.seed), rows: s.rows, cols: s.cols });

/**
 * @param {AppState} s
 * @returns {AppState}
 */
const go_next = (s) => ({ level: s.level + 1, seed: next_seed(s.seed), rows: s.rows, cols: s.cols });

/**
 * @param {AppState} s
 * @returns {AppState}
 */
const go_prev = (s) => ({ level: s.level - 1, seed: next_seed(s.seed), rows: s.rows, cols: s.cols });

/**
 * @param {number} level
 * @param {number} seed
 * @returns {string}
 */
const map_name = (level, seed) => {
  let adj = ["Sunken", "Flooded", "Forgotten", "Ancient", "Crumbling", "Darkened", "Shattered", "Cursed", "Hollow", "Ruined", "Scorched", "Mossy", "Twisted", "Silent", "Pale", "Burning", "Frozen", "Gilded", "Haunted", "Blighted", "Crimson", "Ashen", "Murky", "Lost", "Forsaken", "Tarnished", "Rotting", "Sealed", "Fractured", "Drowned"];
  let noun = ["Hall", "Vault", "Passage", "Chamber", "Catacombs", "Sanctum", "Tomb", "Cavern", "Lair", "Pit", "Maze", "Crypt", "Gallery", "Abyss", "Warren", "Cellar", "Archive", "Ossuary", "Barrow", "Grotto", "Keep", "Depths", "Ruin", "Antechamber", "Oubliette"];
  let h1 = (seed % adj.length + adj.length) % adj.length;
  let h2 = ((seed + level * 7) % noun.length + noun.length) % noun.length;
  return "The " + adj[h1] + " " + noun[h2];
};

const level_description = (level) => ((_m) => (_m === 1) ? "Torch-lit corridors. Watch your step." : (_m === 2) ? "Flooded halls. Not all paths are safe." : (_m === 3) ? "Ancient vaults. Chests shimmer in the gloom." : (_m === 4) ? "The dead rest here. So might you." : (_m === 5) ? "No light reaches this deep." : (level > 5) ? "You shouldn't be here." : "Press onward.")(level);

const render_header = (level, seed) => "<div class=\"dungeon-header\">" + "<h2 class=\"level-name\">Level " + level + " — " + map_name(level, seed) + "</h2>" + "<p class=\"level-desc\">" + level_description(level) + "</p>" + "</div>";

/**
 * @param {AppState} s
 * @returns {*}
 */
const render = (s) => {
  let map = generate(s.rows, s.cols, s.level, s.seed);
  let html = render_header(s.level, s.seed) + render_stats(map, s.seed) + render_map(map) + render_legend();
  document.getElementById("dungeon-output").innerHTML = html;
  document.getElementById("btn-prev").disabled = s.level <= 1;
  document.getElementById("btn-new").onclick = () => render(new_map(s));
  document.getElementById("btn-next").onclick = () => render(go_next(s));
  return document.getElementById("btn-prev").onclick = () => {
    if (s.level > 1) {
      return render(go_prev(s));
    }
};
};

/**
 * @returns {*}
 */
const mount = () => render(init());

mount();

