// Auto-generated by tools/embed_music.js — do not edit manually
window.MUSIC_SOURCES = {
  syn: `// ═══════════════════════════════════════════════════════════════════════════════
// Synth v1.0 — Synthwave Music Library
//
// Every feature from v0.1 through v0.3, demonstrated in one coherent app:
//
//   v0.1  type aliases · records · @intent · @pure · @total · @effects
//         pipeline |> · match patterns · let bindings
//   v0.2  where constraints · short-form fn · stdlib (map/filter/sum/count/any)
//         @pure checker · @exhaustive checker
//   v0.3  string interpolation "{name}" · .field accessor shorthand
//         param validation injection · @memo memoization
// ═══════════════════════════════════════════════════════════════════════════════

// ── v0.2: Constrained types ───────────────────────────────────────────────────
// Every \`where\` clause generates a __validate_T(v) function at compile time.
// Functions typed with these as params get auto-injected guards (v0.3 feature).

type BPM        = int    where >= 60 && <= 200
type Duration   = int    where > 0
type TrackTitle, ArtistName = string where length > 0
type Volume     = int    where >= 0 && <= 100

// ── v0.1: Record declarations ─────────────────────────────────────────────────

record Track {
  id: int
  title: string
  artist: string
  bpm: int
  duration: int
  genre: string
  featured: bool
}

record LibraryStats {
  count: int
  totalDuration: int
  avgBpm: int
  featuredCount: int
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.2: SHORT-FORM FUNCTIONS
// Single-expression functions with no type signature.
// ══════════════════════════════════════════════════════════════════════════════

fn track_is_featured(t) = t.featured

// Helper used in format_duration
fn pad2(n) = n < 10 ? "0" + String(n) : String(n)

// v0.3: string interpolation — {t.title} and {t.artist} are ident.prop forms
fn format_track_label(t) = "{t.title} · {t.artist}"

// v0.3: {bpm} is interpolated, " BPM" is literal
fn format_bpm_tag(bpm) = "{bpm} BPM"

// v0.3: format_fibonacci_result uses two idents in one interpolated string
fn format_fibonacci_result(n, result) = "fib({n}) = {result}"

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: STRING INTERPOLATION in full-form functions
// Local let bindings are used as interpolation targets.
// ══════════════════════════════════════════════════════════════════════════════

@intent "Format seconds as M:SS display string"
@pure @total
fn format_duration :: (secs: Duration) -> string {
  let m = Math.floor(secs / 60)
  let s = pad2(secs % 60)
  "{m}:{s}"
}

@intent "Render a compact one-line summary of library state"
@pure @total
fn format_stats_line :: (stats: LibraryStats) -> string {
  let n    = stats.count
  let mins = Math.floor(stats.totalDuration / 60)
  let avg  = stats.avgBpm
  let feat = stats.featuredCount
  "{n} tracks · {mins} min · avg {avg} BPM · {feat} featured"
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: PARAM VALIDATION INJECTION
// The compiler auto-injects __validate_T guards for constrained-type params.
// No manual validation calls — these guards appear in the transpiled output.
// ══════════════════════════════════════════════════════════════════════════════

@intent "Construct a Track — BPM/Duration/TrackTitle/ArtistName guards injected at entry"
@pure @total
fn create_track :: (id: int, title: TrackTitle, artist: ArtistName, bpm: BPM, duration: Duration, genre: string) -> Track {
  { id, title, artist, bpm, duration, genre, featured: false }
}

@intent "Format a volume level string — Volume must be 0-100 or auto-guard throws"
@pure @total
fn set_volume :: (vol: Volume) -> string {
  "Volume set to {vol}%"
}

// Pre-validation helper for the add-track form (user-facing errors)
@intent "Return the first validation error for new track fields, or empty string if valid"
@pure @total
fn validate_track_input :: (title: string, artist: string, bpm: int, duration: int) -> string {
  title.length === 0   ? "Title cannot be empty" :
  artist.length === 0  ? "Artist cannot be empty" :
  bpm < 60             ? "BPM too low (minimum is 60)" :
  bpm > 200            ? "BPM too high (maximum is 200)" :
  duration <= 0        ? "Duration must be greater than 0" :
  ""
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.1: PATTERN MATCHING
// ══════════════════════════════════════════════════════════════════════════════

@intent "Classify BPM range as a human-readable tempo label"
@pure @total
fn tempo_label :: (bpm: int) -> string {
  match bpm {
    | < 90  => "Slow"
    | < 120 => "Moderate"
    | < 150 => "Fast"
    | _     => "Intense"
  }
}

record GenreMeta {
  id:    string
  css:   string
  short: string
}

let GENRE_META = [
  { id: "synthwave",  css: "g-sw",  short: "SW" },
  { id: "darksynth",  css: "g-ds",  short: "DS" },
  { id: "ambient",    css: "g-amb", short: "AMB" },
  { id: "retrowave",  css: "g-rw",  short: "RW" },
  { id: "cyberpunk",  css: "g-cp",  short: "CP" },
]

@intent "Map genre identifier to its accent color CSS class"
@pure @total
fn genre_css_class :: (genre: string) -> string {
  let hit = GENRE_META.find(g => g.id == genre)
  hit ? hit.css : "g-default"
}

@intent "Abbreviated tag for a genre badge"
@pure @total
fn genre_short :: (genre: string) -> string {
  let hit = GENRE_META.find(g => g.id == genre)
  hit ? hit.short : genre
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: @MEMO — automatic memoization at compile time
// @pure @total @memo functions are wrapped in a Map-based cache closure.
// The cache key is JSON.stringify([...args]).
// ══════════════════════════════════════════════════════════════════════════════

@intent "Aggregate stats across the track collection — memoized, O(1) on repeated calls"
@pure @total @memo
fn library_stats :: (tracks: Track[]) -> LibraryStats {
  let total_dur  = tracks |> map(.duration) |> sum
  let total_bpm  = tracks |> map(.bpm) |> sum
  let n_featured = tracks |> filter(.featured) |> count
  {
    count: tracks.length,
    totalDuration: total_dur,
    avgBpm: tracks.length > 0 ? Math.round(total_bpm / tracks.length) : 0,
    featuredCount: n_featured
  }
}

@intent "Classic recursive Fibonacci — @memo turns O(2^n) into O(n) via Map cache"
@pure @total @memo
fn fibonacci :: (n: int) -> int {
  match n {
    | 0 => 0
    | 1 => 1
    | _ => fibonacci(n-1) + fibonacci(n-2)
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: .FIELD ACCESSOR SHORTHAND in pipelines
// .fieldName creates an implicit lambda __x => __x.fieldName.
// Makes filter/map intent immediately readable — no ceremony.
// ══════════════════════════════════════════════════════════════════════════════

@intent "Return only featured tracks using .featured shorthand"
@pure @total
fn featured_tracks :: (tracks: Track[]) -> Track[] {
  tracks |> filter(.featured)
}

@intent "Extract all track titles using .title shorthand"
@pure @total
fn all_titles :: (tracks: Track[]) -> string[] {
  tracks |> map(.title)
}

@intent "Extract all artist names using .artist shorthand"
@pure @total
fn all_artists :: (tracks: Track[]) -> string[] {
  tracks |> map(.artist)
}

@intent "Sum all durations using .duration shorthand"
@pure @total
fn total_playtime :: (tracks: Track[]) -> int {
  tracks |> map(.duration) |> sum
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.2: STDLIB SHOWCASE
// ══════════════════════════════════════════════════════════════════════════════

@intent "Filter tracks to a specific genre"
@pure @total
fn tracks_in_genre :: (tracks: Track[], genre: string) -> Track[] {
  tracks |> filter(t => t.genre === genre)
}

@intent "True if the collection has at least one featured track"
@pure @total
fn any_featured :: (tracks: Track[]) -> bool {
  tracks |> any(.featured)
}

@intent "Return the top n tracks by BPM descending"
@pure @total
fn top_by_bpm :: (tracks: Track[], n: int) -> Track[] {
  // v1.0: sort_by_desc + take — copies instead of mutating, no checker warning
  tracks |> sort_by_desc(.bpm) |> take(n)
}

// @pure checker demo: intentionally impure function warns at compile time
@intent "Debug-log a track — @pure is a lie, checker will warn"
@pure @total
fn debug_track :: (track: Track) -> bool {
  let _ = console.log("debug_track:", track.title)
  true
}

// ══════════════════════════════════════════════════════════════════════════════
// DOM BUILDER — thin imperative layer, @effects declared explicitly
// ══════════════════════════════════════════════════════════════════════════════

@intent "Create a DOM element, set attributes, and append children"
@effects [dom.create, dom.attrs, dom.children]
fn el :: (tag: string, attrs: object, ...children: any[]) -> Element {
  let e = document.createElement(tag)
  let _ = Object.entries(attrs).forEach(([k, v]) => {
    if (k === "class") { e.className = v }
    else if (k === "id") { e.id = v }
    else if (k === "disabled") { e.disabled = v }
    else if (k === "value") { e.value = v }
    else if (k === "placeholder") { e.placeholder = v }
    else if (k === "type") { e.type = v }
    else if (k === "for") { e.setAttribute("for", v) }
    else if (k.startsWith("on")) { e.addEventListener(k.slice(2).toLowerCase(), v) }
    else { e.setAttribute(k, String(v)) }
  })
  let _ = children.flat().forEach(child => {
    if (typeof child === "string") { e.appendChild(document.createTextNode(child)) }
    else if (child instanceof Node) { e.appendChild(child) }
  })
  e
}

@intent "Append a child element into a container element directly"
@effects [dom.write]
fn mount_into :: (container: Element, child: Element) -> void {
  container.appendChild(child)
}

// ── Track card ────────────────────────────────────────────────────────────────

@intent "Render a single track as a styled card"
@effects [dom.create]
fn render_track_card :: (track: Track) -> Element {
  let label  = format_track_label(track)
  let dur    = format_duration(track.duration)
  let bpmtag = format_bpm_tag(track.bpm)
  let tempo  = tempo_label(track.bpm)
  let gclass = genre_css_class(track.genre)
  let gtag   = genre_short(track.genre)
  let cardClass = track.featured ? "track-card track-featured" : "track-card"
  el("div", { class: cardClass },
    el("div", { class: "track-main" },
      el("div", { class: "track-label" }, label),
      el("div", { class: "track-badges" },
        el("span", { class: "badge genre-badge " + gclass }, gtag),
        el("span", { class: "badge tempo-badge" }, tempo),
        el("span", { class: "badge dur-badge" }, dur),
        el("span", { class: "badge bpm-badge" }, bpmtag)
      )
    ),
    track.featured ? el("div", { class: "featured-mark" }, "FEATURED") : el("span", {})
  )
}

// ── Stats bar ─────────────────────────────────────────────────────────────────

@intent "Render the live library stats and @memo benchmark badge"
@effects [dom.create]
fn render_stats_bar :: (tracks: Track[]) -> Element {
  let stats = library_stats(tracks)
  let line  = format_stats_line(stats)
  let fib35 = fibonacci(35)
  let fibLabel = format_fibonacci_result(35, fib35)
  el("div", { class: "stats-bar" },
    el("span", { class: "stats-text" }, line),
    el("span", { class: "memo-badge" }, fibLabel + " (@memo)")
  )
}

// ── Genre filter row ──────────────────────────────────────────────────────────

@intent "Render genre filter pills — active genre is highlighted"
@effects [dom.create]
fn render_genre_filters :: (genres: string[], activeGenre: string, onFilter: any) -> Element {
  let buttons = genres |> map(g =>
    el("button", { class: g === activeGenre ? "filter-btn filter-btn--active" : "filter-btn" },
      g === "all" ? "All Tracks" : g
    )
  )
  let _ = genres.forEach((g, i) => {
    let btn = buttons[i]
    let _ = btn.addEventListener("click", () => onFilter(g))
  })
  el("div", { class: "filter-row" }, ...buttons)
}

// ── Add track form ────────────────────────────────────────────────────────────

@intent "Render an add-track form that demonstrates param validation injection"
@effects [dom.write, dom.create, dom.events]
fn render_add_form :: (container: Element, onAdd: any) -> void {
  let titleIn  = el("input", { type: "text",   class: "form-inp", placeholder: "Title (required)" })
  let artistIn = el("input", { type: "text",   class: "form-inp", placeholder: "Artist (required)" })
  let bpmIn    = el("input", { type: "number", class: "form-inp", placeholder: "BPM 60-200" })
  let durIn    = el("input", { type: "number", class: "form-inp", placeholder: "Duration (seconds)" })
  let genreIn  = el("input", { type: "text",   class: "form-inp", placeholder: "Genre (optional)" })
  let errEl    = el("div",   { class: "form-err" })
  let addBtn   = el("button", { class: "add-btn" }, "Add Track")
  let _ = addBtn.addEventListener("click", () => {
    let title  = titleIn.value
    let artist = artistIn.value
    // v1.0: parse_int returns null on invalid input — ?? 0 makes bad input fail validation
    let bpm    = parse_int(bpmIn.value) ?? 0
    let dur    = parse_int(durIn.value) ?? 0
    let genre  = genreIn.value.length > 0 ? genreIn.value : "other"
    let err    = validate_track_input(title, artist, bpm, dur)
    if (err.length > 0) {
      errEl.textContent = err
    } else {
      errEl.textContent = ""
      let newId = Math.floor(Math.random() * 9000) + 1000
      let track = create_track(newId, title, artist, bpm, dur, genre)
      let _ = onAdd(track)
      let _ = titleIn.value  = ""
      let _ = artistIn.value = ""
      let _ = bpmIn.value    = ""
      let _ = durIn.value    = ""
      let _ = genreIn.value  = ""
    }
  })
  let _ = container.appendChild(
    el("div", { class: "add-form" },
      el("div", { class: "form-header" },
        el("h3", { class: "form-title" }, "Add Track"),
        el("p", { class: "form-note" },
          "create_track() has auto-injected guards for BPM (60-200), Duration (> 0), " +
          "TrackTitle and ArtistName (non-empty). See the transpiled JS tab."
        )
      ),
      el("div", { class: "form-fields" },
        el("div", { class: "form-row" }, titleIn, artistIn),
        el("div", { class: "form-row" }, bpmIn, durIn, genreIn)
      ),
      errEl,
      addBtn
    )
  )
}

// ── Main library renderer ─────────────────────────────────────────────────────

@intent "Bootstrap and mount the full music library UI into a root container"
@effects [dom.write, dom.events, state.mutable]
fn render_library :: (rootId: string, initialTracks: Track[]) -> void {
  let tracks      = initialTracks.slice()
  let activeGenre = "all"
  let genres      = ["all", "synthwave", "darksynth", "ambient", "retrowave", "cyberpunk"]

  let root = document.getElementById(rootId)
  let _ = root.innerHTML = ""

  // Build layout skeleton — children with IDs for refresh targeting
  let statsEl   = el("div", { class: "stats-section" })
  let filtersEl = el("div", { class: "filters-section" })
  let listEl    = el("div", { class: "track-list" })
  let formEl    = el("div", { class: "form-section" })
  let _ = root.appendChild(statsEl)
  let _ = root.appendChild(filtersEl)
  let _ = root.appendChild(listEl)
  let _ = root.appendChild(formEl)

  // refresh re-renders the live parts (stats, filters, track list)
  let refresh = () => {
    statsEl.innerHTML = ""
    let _ = statsEl.appendChild(render_stats_bar(tracks))
    filtersEl.innerHTML = ""
    let _ = filtersEl.appendChild(render_genre_filters(genres, activeGenre, (genre) => {
      activeGenre = genre
      refresh()
    }))
    listEl.innerHTML = ""
    let visible = activeGenre === "all" ? tracks : tracks_in_genre(tracks, activeGenre)
    let _ = visible.forEach(t => listEl.appendChild(render_track_card(t)))
  }

  // Add form only rendered once — calls refresh when a track is successfully added
  render_add_form(formEl, (track) => {
    tracks = [...tracks, track]
    refresh()
  })

  refresh()
}
`,
  js:  `/** @param {number} v @returns {boolean} */
const __validate_BPM = (v) => (v >= 60) && (v <= 200);
/** @param {number} v @returns {boolean} */
const __validate_Duration = (v) => v > 0;
/** @param {string} v @returns {boolean} */
const __validate_TrackTitle = (v) => v.length > 0;
/** @param {string} v @returns {boolean} */
const __validate_ArtistName = (v) => v.length > 0;
/** @param {number} v @returns {boolean} */
const __validate_Volume = (v) => (v >= 0) && (v <= 100);

const Track = (id, title, artist, bpm, duration, genre, featured) => ({ id, title, artist, bpm, duration, genre, featured });

const LibraryStats = (count, totalDuration, avgBpm, featuredCount) => ({ count, totalDuration, avgBpm, featuredCount });

const track_is_featured = (t) => t.featured;

const pad2 = (n) => n < 10 ? "0" + String(n) : String(n);

const format_track_label = (t) => \`\${t.title} · \${t.artist}\`;

const format_bpm_tag = (bpm) => \`\${bpm} BPM\`;

const format_fibonacci_result = (n, result) => \`fib(\${n}) = \${result}\`;

/**
 * @param {Duration} secs
 * @returns {string}
 */
const format_duration = (secs) => {
  if (!__validate_Duration(secs)) throw new Error("SynthConstraintError: secs violates Duration constraint (got " + JSON.stringify(secs) + ")");
  let m = Math.floor(secs / 60);
  let s = pad2(secs % 60);
  return \`\${m}:\${s}\`;
};

/**
 * @param {LibraryStats} stats
 * @returns {string}
 */
const format_stats_line = (stats) => {
  let n = stats.count;
  let mins = Math.floor(stats.totalDuration / 60);
  let avg = stats.avgBpm;
  let feat = stats.featuredCount;
  return \`\${n} tracks · \${mins} min · avg \${avg} BPM · \${feat} featured\`;
};

/**
 * @param {number} id
 * @param {TrackTitle} title
 * @param {ArtistName} artist
 * @param {BPM} bpm
 * @param {Duration} duration
 * @param {string} genre
 * @returns {Track}
 */
const create_track = (id, title, artist, bpm, duration, genre) => {
  if (!__validate_TrackTitle(title)) throw new Error("SynthConstraintError: title violates TrackTitle constraint (got " + JSON.stringify(title) + ")");
  if (!__validate_ArtistName(artist)) throw new Error("SynthConstraintError: artist violates ArtistName constraint (got " + JSON.stringify(artist) + ")");
  if (!__validate_BPM(bpm)) throw new Error("SynthConstraintError: bpm violates BPM constraint (got " + JSON.stringify(bpm) + ")");
  if (!__validate_Duration(duration)) throw new Error("SynthConstraintError: duration violates Duration constraint (got " + JSON.stringify(duration) + ")");
  return ({id, title, artist, bpm, duration, genre, featured: false});
};

/**
 * @param {Volume} vol
 * @returns {string}
 */
const set_volume = (vol) => {
  if (!__validate_Volume(vol)) throw new Error("SynthConstraintError: vol violates Volume constraint (got " + JSON.stringify(vol) + ")");
  return \`Volume set to \${vol}%\`;
};

/**
 * @param {string} title
 * @param {string} artist
 * @param {number} bpm
 * @param {number} duration
 * @returns {string}
 */
const validate_track_input = (title, artist, bpm, duration) => title.length === 0 ? "Title cannot be empty" : artist.length === 0 ? "Artist cannot be empty" : bpm < 60 ? "BPM too low (minimum is 60)" : bpm > 200 ? "BPM too high (maximum is 200)" : duration <= 0 ? "Duration must be greater than 0" : "";

/**
 * @param {number} bpm
 * @returns {string}
 */
const tempo_label = (bpm) => ((_m) => (_m < "90") ? "Slow" : (_m < "120") ? "Moderate" : (_m < "150") ? "Fast" : "Intense")(bpm);

const GenreMeta = (id, css, short) => ({ id, css, short });

let GENRE_META = [{id: "synthwave", css: "g-sw", short: "SW"}, {id: "darksynth", css: "g-ds", short: "DS"}, {id: "ambient", css: "g-amb", short: "AMB"}, {id: "retrowave", css: "g-rw", short: "RW"}, {id: "cyberpunk", css: "g-cp", short: "CP"}];

/**
 * @param {string} genre
 * @returns {string}
 */
const genre_css_class = (genre) => {
  let hit = \$find(GENRE_META, (g) => g.id == genre);
  return hit ? hit.css : "g-default";
};

/**
 * @param {string} genre
 * @returns {string}
 */
const genre_short = (genre) => {
  let hit = \$find(GENRE_META, (g) => g.id == genre);
  return hit ? hit.short : genre;
};

const library_stats = (() => {
  const __cache = new Map();
  return (tracks) => {
    const __key = JSON.stringify([tracks]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      let total_dur = \$sum(\$map(tracks, (__x) => __x.duration));
      let total_bpm = \$sum(\$map(tracks, (__x) => __x.bpm));
      let n_featured = \$count(\$filter(tracks, (__x) => __x.featured));
      return {count: tracks.length, totalDuration: total_dur, avgBpm: tracks.length > 0 ? Math.round(total_bpm / tracks.length) : 0, featuredCount: n_featured};
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

const fibonacci = (() => {
  const __cache = new Map();
  return (n) => {
    const __key = JSON.stringify([n]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return ((_m) => (_m === 0) ? 0 : (_m === 1) ? 1 : fibonacci(n - 1) + fibonacci(n - 2))(n);
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * @param {Track} tracks
 * @returns {Track}
 */
const featured_tracks = (tracks) => \$filter(tracks, (__x) => __x.featured);

/**
 * @param {Track} tracks
 * @returns {string}
 */
const all_titles = (tracks) => \$map(tracks, (__x) => __x.title);

/**
 * @param {Track} tracks
 * @returns {string}
 */
const all_artists = (tracks) => \$map(tracks, (__x) => __x.artist);

/**
 * @param {Track} tracks
 * @returns {number}
 */
const total_playtime = (tracks) => \$sum(\$map(tracks, (__x) => __x.duration));

/**
 * @param {Track} tracks
 * @param {string} genre
 * @returns {Track}
 */
const tracks_in_genre = (tracks, genre) => \$filter(tracks, (t) => t.genre === genre);

/**
 * @param {Track} tracks
 * @returns {boolean}
 */
const any_featured = (tracks) => \$any(tracks, (__x) => __x.featured);

/**
 * @param {Track} tracks
 * @param {number} n
 * @returns {Track}
 */
const top_by_bpm = (tracks, n) => \$take(\$sort_by_desc(tracks, (__x) => __x.bpm), n);

/**
 * @param {Track} track
 * @returns {boolean}
 */
const debug_track = (track) => {
  console.log("debug_track:", track.title);
  return true;
};

/**
 * @param {string} tag
 * @param {object} attrs
 * @param {*} ...children
 * @returns {Element}
 */
const el = (tag, attrs, ...children) => {
  let e = document.createElement(tag);
  Object.entries(attrs).forEach(([k, v]) => (() => {
    if (k === "class") {
      return e.className = v;
    } else if (k === "id") {
      return e.id = v;
    } else if (k === "disabled") {
      return e.disabled = v;
    } else if (k === "value") {
      return e.value = v;
    } else if (k === "placeholder") {
      return e.placeholder = v;
    } else if (k === "type") {
      return e.type = v;
    } else if (k === "for") {
      return e.setAttribute("for", v);
    } else if (k.startsWith("on")) {
      return e.addEventListener(k.slice(2).toLowerCase(), v);
    } else {
      return e.setAttribute(k, String(v));
    }
})());
  \$flat(children).forEach((child) => (() => {
    if (typeof child === "string") {
      return e.appendChild(document.createTextNode(child));
    } else if (child instanceof Node) {
      return e.appendChild(child);
    }
})());
  return e;
};

/**
 * @param {Element} container
 * @param {Element} child
 * @returns {void}
 */
const mount_into = (container, child) => container.appendChild(child);

/**
 * @param {Track} track
 * @returns {Element}
 */
const render_track_card = (track) => {
  let label = format_track_label(track);
  let dur = format_duration(track.duration);
  let bpmtag = format_bpm_tag(track.bpm);
  let tempo = tempo_label(track.bpm);
  let gclass = genre_css_class(track.genre);
  let gtag = genre_short(track.genre);
  let cardClass = track.featured ? "track-card track-featured" : "track-card";
  return el("div", {class: cardClass}, el("div", {class: "track-main"}, el("div", {class: "track-label"}, label), el("div", {class: "track-badges"}, el("span", {class: "badge genre-badge " + gclass}, gtag), el("span", {class: "badge tempo-badge"}, tempo), el("span", {class: "badge dur-badge"}, dur), el("span", {class: "badge bpm-badge"}, bpmtag))), track.featured ? el("div", {class: "featured-mark"}, "FEATURED") : el("span", {}));
};

/**
 * @param {Track} tracks
 * @returns {Element}
 */
const render_stats_bar = (tracks) => {
  let stats = library_stats(tracks);
  let line = format_stats_line(stats);
  let fib35 = fibonacci(35);
  let fibLabel = format_fibonacci_result(35, fib35);
  return el("div", {class: "stats-bar"}, el("span", {class: "stats-text"}, line), el("span", {class: "memo-badge"}, fibLabel + " (@memo)"));
};

/**
 * @param {string} genres
 * @param {string} activeGenre
 * @param {*} onFilter
 * @returns {Element}
 */
const render_genre_filters = (genres, activeGenre, onFilter) => {
  let buttons = \$map(genres, (g) => el("button", {class: g === activeGenre ? "filter-btn filter-btn--active" : "filter-btn"}, g === "all" ? "All Tracks" : g));
  genres.forEach((g, i) => (() => {
    let btn = buttons[i];
    btn.addEventListener("click", () => onFilter(g));
})());
  return el("div", {class: "filter-row"}, ...buttons);
};

/**
 * @param {Element} container
 * @param {*} onAdd
 * @returns {void}
 */
const render_add_form = (container, onAdd) => {
  let titleIn = el("input", {type: "text", class: "form-inp", placeholder: "Title (required)"});
  let artistIn = el("input", {type: "text", class: "form-inp", placeholder: "Artist (required)"});
  let bpmIn = el("input", {type: "number", class: "form-inp", placeholder: "BPM 60-200"});
  let durIn = el("input", {type: "number", class: "form-inp", placeholder: "Duration (seconds)"});
  let genreIn = el("input", {type: "text", class: "form-inp", placeholder: "Genre (optional)"});
  let errEl = el("div", {class: "form-err"});
  let addBtn = el("button", {class: "add-btn"}, "Add Track");
  addBtn.addEventListener("click", () => (() => {
    let title = titleIn.value;
    let artist = artistIn.value;
    let bpm = \$parse_int(bpmIn.value) ?? 0;
    let dur = \$parse_int(durIn.value) ?? 0;
    let genre = genreIn.value.length > 0 ? genreIn.value : "other";
    let err = validate_track_input(title, artist, bpm, dur);
    if (err.length > 0) {
      return errEl.textContent = err;
    } else {
      errEl.textContent = "";
      let newId = Math.floor(Math.random() * 9000) + 1000;
      let track = create_track(newId, title, artist, bpm, dur, genre);
      onAdd(track);
      titleIn.value = "";
      artistIn.value = "";
      bpmIn.value = "";
      durIn.value = "";
      genreIn.value = "";
    }
})());
  container.appendChild(el("div", {class: "add-form"}, el("div", {class: "form-header"}, el("h3", {class: "form-title"}, "Add Track"), el("p", {class: "form-note"}, "create_track() has auto-injected guards for BPM (60-200), Duration (> 0), " + "TrackTitle and ArtistName (non-empty). See the transpiled JS tab.")), el("div", {class: "form-fields"}, el("div", {class: "form-row"}, titleIn, artistIn), el("div", {class: "form-row"}, bpmIn, durIn, genreIn)), errEl, addBtn));
};

/**
 * @param {string} rootId
 * @param {Track} initialTracks
 * @returns {void}
 */
const render_library = (rootId, initialTracks) => {
  let tracks = initialTracks.slice();
  let activeGenre = "all";
  let genres = ["all", "synthwave", "darksynth", "ambient", "retrowave", "cyberpunk"];
  let root = document.getElementById(rootId);
  root.innerHTML = "";
  let statsEl = el("div", {class: "stats-section"});
  let filtersEl = el("div", {class: "filters-section"});
  let listEl = el("div", {class: "track-list"});
  let formEl = el("div", {class: "form-section"});
  root.appendChild(statsEl);
  root.appendChild(filtersEl);
  root.appendChild(listEl);
  root.appendChild(formEl);
  let refresh = () => (() => {
    statsEl.innerHTML = "";
    statsEl.appendChild(render_stats_bar(tracks));
    filtersEl.innerHTML = "";
    filtersEl.appendChild(render_genre_filters(genres, activeGenre, (genre) => (() => {
      activeGenre = genre;
      return refresh();
})()));
    listEl.innerHTML = "";
    let visible = activeGenre === "all" ? tracks : tracks_in_genre(tracks, activeGenre);
    visible.forEach((t) => listEl.appendChild(render_track_card(t)));
})();
  render_add_form(formEl, (track) => (() => {
    tracks = [...tracks, track];
    return refresh();
})());
  return refresh();
};

`,
};
