// Auto-generated by tools/embed_sources.js — do not edit manually
window.SYNTH_SOURCES = {
  axn: `// ═══════════════════════════════════════════════════════════════════════════════
// Synth v1.0 — Web Controls Demo
//
// Features exercised below:
//
//   • String interpolation — "Hello {name}" compiles to template literals
//   • .field accessor shorthand — filter(.active), map(.score) in pipelines
//   • Param validation injection — typed params with \`where\` get auto-guards
//   • @memo annotation — @pure @total functions get Map-based cache wrappers
//   • Spread record updates — { ...state, count: n } (v0.9.9)
// ═══════════════════════════════════════════════════════════════════════════════

// ── Constrained types ──────────────────────────────────────────────────────────
// Every \`where\` clause generates a __validate_T(v) function at compile time.
// Any function that declares a param with one of these types gets an auto-injected
// guard at entry — no manual validation calls needed.

type NonEmptyString = string where length > 0
type EmailAddress   = string where matches(#email)
type PositiveInt    = int    where > 0
type Score          = int    where >= 0 && <= 100
type BoundedCount   = int    where >= -10 && <= 10
type CSSClass       = string where length > 0
type ThemeName      = string
type SlugString     = string where matches(#slug)

// ── Data shapes ────────────────────────────────────────────────────────────────

record CounterState {
  count: int
  min: int
  max: int
}

record ValidationResult {
  valid: bool
  message: string
  value: string
}

record ModalState {
  open: bool
  title: string
  body: string
}

// NEW v0.3: used to showcase .field shorthand in pipelines
record Player {
  name: string
  score: Score
  active: bool
}

// ══════════════════════════════════════════════════════════════════════════════
// COUNTER
// ══════════════════════════════════════════════════════════════════════════════

fn counter_make(min, max, initial) =
  { count: clamp(initial, min, max), min, max }

// Spread record updates — copy the state, change one field
fn counter_inc(state) = { ...state, count: Math.min(state.count + 1, state.max) }
fn counter_dec(state) = { ...state, count: Math.max(state.count - 1, state.min) }

fn counter_can_inc(state) = state.count < state.max
fn counter_can_dec(state) = state.count > state.min

fn counter_display :: (state: CounterState) -> string {
  @pure @total
  @intent "Format counter value as a signed display string"
  // v0.3: string interpolation — "+{n}" compiles to \`+\${n}\` automatically
  let n = state.count
  match n {
    | > 0 => "+{n}"
    | < 0 => "{n}"
    | _   => "0"
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// EMAIL VALIDATOR
// ══════════════════════════════════════════════════════════════════════════════

fn is_valid_email(email) = __validate_EmailAddress(email)

fn validate_email :: (email: string) -> ValidationResult {
  @pure @total
  @intent "Produce a structured validation result with human-readable feedback"
  match email.length {
    | 0 => { valid: false, message: "Email is required", value: email }
    | _ => match is_valid_email(email) {
        | true  => { valid: true,  message: "Looks good!",               value: email }
        | false => { valid: false, message: "Enter a valid email address", value: email }
      }
  }
}

fn validation_css_class(result) =
  result.valid ? "field-valid"
               : result.value.length === 0 ? "field-empty" : "field-invalid"

// ══════════════════════════════════════════════════════════════════════════════
// TOGGLE
// ══════════════════════════════════════════════════════════════════════════════

fn toggle_flip(state) = !state

fn toggle_label(state, onLabel, offLabel) = state ? onLabel : offLabel

// v0.3: string interpolation makes the class composition readable
fn toggle_css_class(state, baseClass) =
  state ? "{baseClass} {baseClass}--on"
        : "{baseClass} {baseClass}--off"

// ══════════════════════════════════════════════════════════════════════════════
// THEME
// ══════════════════════════════════════════════════════════════════════════════

// v0.3: "theme-{name}" compiles to \`theme-\${name}\` — no concatenation needed
fn theme_class(name) = "theme-{name}"

fn theme_next(current, available) =
  available[(available.indexOf(current) + 1) % available.length]

fn theme_label :: (name: ThemeName) -> string {
  @pure @total
  @intent "Human-readable display label for a named theme"
  match name {
    | "light"     => "Light"
    | "dark"      => "Dark"
    | "synthwave" => "Synthwave"
    | _           => name
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// MODAL
// ══════════════════════════════════════════════════════════════════════════════

fn modal_open(title, body) = { open: true, title, body }

fn modal_close(state) = { ...state, open: false }

// ══════════════════════════════════════════════════════════════════════════════
// PARAM VALIDATION INJECTION — v0.3 feature
//
// Functions typed with constrained-type params get automatic guard clauses
// injected at the top of the function body. No manual __validate_* calls.
// The transpiler sees \`email: EmailAddress\` and inserts:
//   if (!__validate_EmailAddress(email)) throw new Error(...)
// ══════════════════════════════════════════════════════════════════════════════

fn send_welcome :: (email: EmailAddress, name: NonEmptyString) -> string {
  @pure @total
  @intent "Format a welcome message — params are auto-validated at the boundary"
  "Welcome, {name}! A confirmation has been sent to {email}."
}

fn format_score :: (label: NonEmptyString, value: Score) -> string {
  @pure @total
  @intent "Format a score label — Score type ensures 0-100, NonEmptyString ensures label exists"
  "{label}: {value}/100"
}

// ══════════════════════════════════════════════════════════════════════════════
// .FIELD ACCESSOR SHORTHAND — v0.3 feature
//
// \`.fieldName\` in any expression position creates an implicit lambda:
//   __x => __x.fieldName
// This makes pipelines cleaner and closer to what the AI intends to say.
// ══════════════════════════════════════════════════════════════════════════════

// v0.3: map(.count) instead of map(s => s.count)
fn counter_history_total :: (states: CounterState[]) -> int {
  @pure @total
  @intent "Sum the counts from an array of counter states"
  states |> map(.count) |> sum
}

// v0.3: filter(.active) |> map(.name) — intent is immediately readable
fn top_players :: (players: Player[]) -> string[] {
  @pure @total
  @intent "Get names of all active players"
  players |> filter(.active) |> map(.name)
}

// v0.3: chained accessor .score for a clean extraction pipeline
fn total_score :: (players: Player[]) -> int {
  @pure @total
  @intent "Sum all player scores"
  players |> map(.score) |> sum
}

// ══════════════════════════════════════════════════════════════════════════════
// @MEMO ANNOTATION — v0.3 feature
//
// @memo wraps the function in a Map-based memoization closure at compile time.
// Every unique set of arguments is cached after the first call.
// Recursive functions benefit automatically — fib(40) no longer re-computes.
// Combined with @pure @total: if it's pure and total, it's safe to memoize.
// ══════════════════════════════════════════════════════════════════════════════

fn fibonacci :: (n: int) -> int {
  @pure @total @memo
  @intent "Classic recursive Fibonacci — automatically memoized by @memo"
  match n {
    | 0 => 0
    | 1 => 1
    | _ => fibonacci(n-1) + fibonacci(n-2)
  }
}

fn triangle_number :: (n: int) -> int {
  @pure @total @memo
  @intent "n*(n+1)/2 — memoized for repeated calls with same n"
  n * (n + 1) / 2
}

// ══════════════════════════════════════════════════════════════════════════════
// STDLIB SHOWCASE — pipelines with .field shorthand and interpolation
// ══════════════════════════════════════════════════════════════════════════════

fn validate_email_batch :: (emails: string[]) -> ValidationResult[] {
  @pure @total
  @intent "Validate every email in a list and return all results"
  emails |> map(validate_email)
}

fn count_valid_emails :: (emails: string[]) -> int {
  @pure @total
  @intent "Count how many emails in a list pass validation"
  emails |> filter(is_valid_email) |> count
}

fn first_invalid_email :: (emails: string[]) -> string {
  @pure @total
  @intent "Return the first invalid email, or empty string if all pass"
  // v1.0: find + nullish coalescing replaces filter-then-check
  emails.find(e => !is_valid_email(e)) ?? ""
}

fn theme_options :: (themes: string[]) -> string[] {
  @pure @total
  @intent "Map theme names to their display labels"
  themes |> map(theme_label)
}

fn any_at_max :: (states: CounterState[]) -> bool {
  @pure @total
  @intent "True if any counter state has reached its maximum value"
  states |> any(s => s.count === s.max)
}

// ══════════════════════════════════════════════════════════════════════════════
// @PURE CHECKER DEMO — intentional warning to show the checker works
// ══════════════════════════════════════════════════════════════════════════════

fn debug_validate :: (email: string) -> bool {
  @pure @total
  @intent "Validate email with debug logging — intentionally impure to demo checker"
  let result = is_valid_email(email)
  let _ = console.log("debug_validate:", email, "->", result)
  result
}

// ══════════════════════════════════════════════════════════════════════════════
// DOM BUILDER — thin imperative layer
// ══════════════════════════════════════════════════════════════════════════════

fn el :: (tag: string, attrs: object, ...children: any[]) -> Element {
  @effects [dom.create, dom.attrs, dom.children]
  @intent "Create a DOM element, apply attributes, and append children"
  let e = document.createElement(tag)
  let _ = Object.entries(attrs).forEach(([k, v]) => {
    if (k === "class") { e.className = v }
    else if (k === "disabled") { e.disabled = v }
    else if (k === "checked") { e.checked = v }
    else if (k.startsWith("on")) { e.addEventListener(k.slice(2).toLowerCase(), v) }
    else if (k === "placeholder") { e.placeholder = v }
    else if (k === "type") { e.type = v }
    else if (k === "value") { e.value = v }
    else if (k === "id") { e.id = v }
    else if (k === "for") { e.setAttribute("for", v) }
    else { e.setAttribute(k, String(v)) }
  })
  let _ = children.flat().forEach(child => {
    if (typeof child === "string") { e.appendChild(document.createTextNode(child)) }
    else if (child instanceof Node) { e.appendChild(child) }
  })
  e
}

fn mount :: (containerId: string, child: Element) -> void {
  @effects [dom.write]
  @intent "Append a child element into a container by ID"
  let container = document.getElementById(containerId)
  container.appendChild(child)
}

// ══════════════════════════════════════════════════════════════════════════════
// COUNTER WIDGET
// ══════════════════════════════════════════════════════════════════════════════

fn render_counter :: (containerId: string) -> void {
  @effects [dom.write, dom.events, state.mutable]
  @intent "Mount a stateful counter widget"
  let state = counter_make(-10, 10, 0)
  let display = el("span", { class: "counter-value" }, counter_display(state))
  let decBtn = el("button", { class: "btn btn-ghost" }, "−")
  let incBtn = el("button", { class: "btn btn-ghost" }, "+")
  let _ = decBtn.addEventListener("click", () => {
    state = counter_dec(state)
    display.textContent = counter_display(state)
    decBtn.disabled = !counter_can_dec(state)
    incBtn.disabled = !counter_can_inc(state)
  })
  let _ = incBtn.addEventListener("click", () => {
    state = counter_inc(state)
    display.textContent = counter_display(state)
    decBtn.disabled = !counter_can_dec(state)
    incBtn.disabled = !counter_can_inc(state)
  })
  mount(containerId, el("div", { class: "counter-widget" }, decBtn, display, incBtn))
}

// ══════════════════════════════════════════════════════════════════════════════
// EMAIL VALIDATOR WIDGET
// ══════════════════════════════════════════════════════════════════════════════

fn render_email_validator :: (containerId: string) -> void {
  @effects [dom.write, dom.events, state.mutable]
  @intent "Mount an email input widget with live validation feedback"
  let input    = el("input", { type: "email", class: "input-field", placeholder: "you@example.com", id: "email-input" })
  let feedback = el("span",  { class: "field-empty feedback-msg" }, "Enter your email")
  let _ = input.addEventListener("input", () => {
    let result = validate_email(input.value)
    feedback.textContent = result.message
    feedback.className   = validation_css_class(result) + " feedback-msg"
    input.className      = "input-field " + validation_css_class(result)
  })
  mount(containerId,
    el("div", { class: "validator-widget" },
      el("label", { for: "email-input", class: "field-label" }, "Email Address"),
      input,
      feedback
    )
  )
}

// ══════════════════════════════════════════════════════════════════════════════
// TOGGLE WIDGET
// ══════════════════════════════════════════════════════════════════════════════

fn render_toggle :: (containerId: string, onLabel: string, offLabel: string) -> void {
  @effects [dom.write, dom.events, state.mutable]
  @intent "Mount a toggle switch that flips between two labelled states"
  let state = false
  let track = el("div",  { class: toggle_css_class(state, "toggle-track") })
  let thumb = el("div",  { class: "toggle-thumb" })
  let label = el("span", { class: "toggle-label" }, toggle_label(state, onLabel, offLabel))
  let _ = track.appendChild(thumb)
  let btn = el("button", { class: "toggle-btn" }, track, label)
  let _ = btn.addEventListener("click", () => {
    state = toggle_flip(state)
    track.className  = toggle_css_class(state, "toggle-track")
    label.textContent = toggle_label(state, onLabel, offLabel)
  })
  mount(containerId, btn)
}

// ══════════════════════════════════════════════════════════════════════════════
// THEME SWITCHER WIDGET
// ══════════════════════════════════════════════════════════════════════════════

fn render_theme_switcher :: (containerId: string) -> void {
  @effects [dom.write, dom.events, state.mutable]
  @intent "Mount a button that cycles through available themes"
  let themes  = ["light", "dark", "synthwave"]
  let labels  = theme_options(themes)
  let current = 0
  let _ = document.body.className = theme_class(themes[current])
  let lbl = el("span", { class: "theme-label" }, labels[current])
  let ico = el("span", { class: "theme-icon" }, "◐")
  let btn = el("button", { class: "btn btn-theme" }, ico, lbl)
  let _ = btn.addEventListener("click", () => {
    current = (current + 1) % themes.length
    document.body.className = theme_class(themes[current])
    lbl.textContent = labels[current]
  })
  mount(containerId, btn)
}

// ══════════════════════════════════════════════════════════════════════════════
// MODAL WIDGET
// ══════════════════════════════════════════════════════════════════════════════

fn render_modal_demo :: (containerId: string) -> void {
  @effects [dom.write, dom.events, state.mutable]
  @intent "Mount a button that opens a modal dialog"
  let state    = modal_close({ open: false, title: "", body: "" })
  let closeBtn = el("button", { class: "btn btn-primary modal-close-btn" }, "Close")
  let overlay  = el("div", { class: "modal-overlay" },
    el("div", { class: "modal-box" },
      el("h3", { class: "modal-title" }, "Hello from Synth"),
      el("p",  { class: "modal-body" },
        "This modal state is managed by pure Synth functions. " +
        "Opening and closing are just state transitions — no framework needed."
      ),
      closeBtn
    )
  )
  let openBtn = el("button", { class: "btn btn-primary", id: "modal-open" }, "Open Modal")
  let _ = openBtn.addEventListener("click", () => {
    state = modal_open("Hello from Synth", "Pure state logic")
    overlay.style.display = "flex"
  })
  let _ = closeBtn.addEventListener("click", () => {
    state = modal_close(state)
    overlay.style.display = "none"
  })
  let _ = overlay.addEventListener("click", e => {
    if (e.target === overlay) {
      state = modal_close(state)
      overlay.style.display = "none"
    }
  })
  let _ = document.body.appendChild(overlay)
  mount(containerId, openBtn)
}
`,
  ts:  `// ═══════════════════════════════════════════════════════════════════════════════
// TypeScript — Web Controls Demo (comparison file)
// Equivalent functionality to controls.syn
// ═══════════════════════════════════════════════════════════════════════════════

// ── Types ──────────────────────────────────────────────────────────────────────
// TypeScript has no semantic constraint types — we use branded types as an idiom,
// but they require explicit casting and do not document intent at the type level.

type NonEmptyString = string
type EmailAddress = string
type PositiveInt = number
type CSSClass = string
type ThemeName = "light" | "dark" | "synthwave"

// ── Interfaces ─────────────────────────────────────────────────────────────────

interface CounterState {
  count: number
  min: number
  max: number
}

interface ValidationResult {
  valid: boolean
  message: string
  value: string
}

interface ModalState {
  open: boolean
  title: string
  body: string
}

// ══════════════════════════════════════════════════════════════════════════════
// COUNTER
// ══════════════════════════════════════════════════════════════════════════════

function counter_make(min: number, max: number, initial: number): CounterState {
  return { count: Math.max(min, Math.min(max, initial)), min, max }
}

function counter_inc(state: CounterState): CounterState {
  return { ...state, count: Math.min(state.count + 1, state.max) }
}

function counter_dec(state: CounterState): CounterState {
  return { ...state, count: Math.max(state.count - 1, state.min) }
}

function counter_can_inc(state: CounterState): boolean {
  return state.count < state.max
}

function counter_can_dec(state: CounterState): boolean {
  return state.count > state.min
}

function counter_display(state: CounterState): string {
  if (state.count > 0) return \`+\${state.count}\`
  if (state.count < 0) return String(state.count)
  return "0"
}

// ══════════════════════════════════════════════════════════════════════════════
// EMAIL VALIDATOR
// ══════════════════════════════════════════════════════════════════════════════

function is_valid_email(email: string): boolean {
  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+\$/.test(email)
}

function validate_email(email: string): ValidationResult {
  if (email.length === 0) {
    return { valid: false, message: "Email is required", value: email }
  }
  if (is_valid_email(email)) {
    return { valid: true, message: "Looks good!", value: email }
  }
  return { valid: false, message: "Enter a valid email address", value: email }
}

function validation_css_class(result: ValidationResult): CSSClass {
  if (result.valid) return "field-valid"
  if (result.value.length === 0) return "field-empty"
  return "field-invalid"
}

// ══════════════════════════════════════════════════════════════════════════════
// TOGGLE
// ══════════════════════════════════════════════════════════════════════════════

function toggle_flip(state: boolean): boolean {
  return !state
}

function toggle_label(state: boolean, onLabel: string, offLabel: string): string {
  return state ? onLabel : offLabel
}

function toggle_css_class(state: boolean, baseClass: string): CSSClass {
  return state ? \`\${baseClass} \${baseClass}--on\` : \`\${baseClass} \${baseClass}--off\`
}

// ══════════════════════════════════════════════════════════════════════════════
// THEME
// ══════════════════════════════════════════════════════════════════════════════

const THEME_LABELS: Record<ThemeName, string> = {
  light: "Light",
  dark: "Dark",
  synthwave: "Synthwave",
}

function theme_class(name: ThemeName): CSSClass {
  return \`theme-\${name}\`
}

function theme_next(current: ThemeName, available: ThemeName[]): ThemeName {
  const idx = available.indexOf(current)
  return available[(idx + 1) % available.length]
}

function theme_label(name: ThemeName): string {
  return THEME_LABELS[name] ?? name
}

// ══════════════════════════════════════════════════════════════════════════════
// MODAL
// ══════════════════════════════════════════════════════════════════════════════

function modal_open(title: string, body: string): ModalState {
  return { open: true, title, body }
}

function modal_close(state: ModalState): ModalState {
  return { ...state, open: false }
}

// ══════════════════════════════════════════════════════════════════════════════
// DOM BUILDER
// ══════════════════════════════════════════════════════════════════════════════

type AttrMap = Record<string, string | boolean | number | EventListener>

function el(tag: string, attrs: AttrMap, ...children: (string | Node)[]): HTMLElement {
  const e = document.createElement(tag)
  for (const [k, v] of Object.entries(attrs)) {
    if (k === "class")       { e.className = String(v) }
    else if (k === "disabled") { (e as HTMLButtonElement).disabled = Boolean(v) }
    else if (k === "checked")  { (e as HTMLInputElement).checked = Boolean(v) }
    else if (k.startsWith("on")) { e.addEventListener(k.slice(2).toLowerCase(), v as EventListener) }
    else if (k === "placeholder") { (e as HTMLInputElement).placeholder = String(v) }
    else if (k === "type")   { (e as HTMLInputElement).type = String(v) }
    else if (k === "value")  { (e as HTMLInputElement).value = String(v) }
    else if (k === "id")     { e.id = String(v) }
    else if (k === "for")    { e.setAttribute("for", String(v)) }
    else { e.setAttribute(k, String(v)) }
  }
  children.flat().forEach(child => {
    if (typeof child === "string") e.appendChild(document.createTextNode(child))
    else if (child instanceof Node) e.appendChild(child)
  })
  return e
}

function mount(containerId: string, child: HTMLElement): void {
  const container = document.getElementById(containerId)
  if (container) container.appendChild(child)
}

// ══════════════════════════════════════════════════════════════════════════════
// COUNTER WIDGET
// ══════════════════════════════════════════════════════════════════════════════

function render_counter(containerId: string): void {
  let state = counter_make(-10, 10, 0)
  const display = el("span", { class: "counter-value" }, counter_display(state))
  const decBtn = el("button", { class: "btn btn-ghost", id: "dec-btn" }, "−")
  const incBtn = el("button", { class: "btn btn-ghost", id: "inc-btn" }, "+")

  decBtn.addEventListener("click", () => {
    state = counter_dec(state)
    display.textContent = counter_display(state)
    ;(decBtn as HTMLButtonElement).disabled = !counter_can_dec(state)
    ;(incBtn as HTMLButtonElement).disabled = !counter_can_inc(state)
  })

  incBtn.addEventListener("click", () => {
    state = counter_inc(state)
    display.textContent = counter_display(state)
    ;(decBtn as HTMLButtonElement).disabled = !counter_can_dec(state)
    ;(incBtn as HTMLButtonElement).disabled = !counter_can_inc(state)
  })

  const widget = el("div", { class: "counter-widget" }, decBtn, display, incBtn)
  mount(containerId, widget)
}

// ══════════════════════════════════════════════════════════════════════════════
// EMAIL VALIDATOR WIDGET
// ══════════════════════════════════════════════════════════════════════════════

function render_email_validator(containerId: string): void {
  const input = el("input", {
    type: "email",
    class: "input-field",
    placeholder: "you@example.com",
    id: "email-input",
  }) as HTMLInputElement

  const feedback = el("span", { class: "field-empty feedback-msg" }, "Enter your email")

  input.addEventListener("input", () => {
    const result = validate_email(input.value)
    feedback.textContent = result.message
    feedback.className = \`\${validation_css_class(result)} feedback-msg\`
    input.className = \`input-field \${validation_css_class(result)}\`
  })

  const widget = el("div", { class: "validator-widget" },
    el("label", { for: "email-input", class: "field-label" }, "Email Address"),
    input,
    feedback
  )
  mount(containerId, widget)
}

// ══════════════════════════════════════════════════════════════════════════════
// TOGGLE WIDGET
// ══════════════════════════════════════════════════════════════════════════════

function render_toggle(containerId: string, onLabel: string, offLabel: string): void {
  let state = false
  const track = el("div", { class: toggle_css_class(state, "toggle-track") })
  const thumb = el("div", { class: "toggle-thumb" })
  const label = el("span", { class: "toggle-label" }, toggle_label(state, onLabel, offLabel))
  track.appendChild(thumb)
  const btn = el("button", { class: "toggle-btn" }, track, label)
  btn.addEventListener("click", () => {
    state = toggle_flip(state)
    track.className = toggle_css_class(state, "toggle-track")
    label.textContent = toggle_label(state, onLabel, offLabel)
  })
  mount(containerId, btn)
}

// ══════════════════════════════════════════════════════════════════════════════
// THEME SWITCHER WIDGET
// ══════════════════════════════════════════════════════════════════════════════

function render_theme_switcher(containerId: string): void {
  const themes: ThemeName[] = ["light", "dark", "synthwave"]
  let current: ThemeName = "light"
  document.body.className = theme_class(current)

  const label = el("span", { class: "theme-label" }, theme_label(current))
  const icon = el("span", { class: "theme-icon" }, "◐")
  const btn = el("button", { class: "btn btn-theme" }, icon, label)

  btn.addEventListener("click", () => {
    current = theme_next(current, themes)
    document.body.className = theme_class(current)
    label.textContent = theme_label(current)
  })

  mount(containerId, btn)
}

// ══════════════════════════════════════════════════════════════════════════════
// MODAL WIDGET
// ══════════════════════════════════════════════════════════════════════════════

function render_modal_demo(containerId: string): void {
  let state = modal_close({ open: false, title: "", body: "" })

  const overlay = el("div", { class: "modal-overlay", id: "modal-overlay" },
    el("div", { class: "modal-box" },
      el("h3", { class: "modal-title" }, "Hello from TypeScript"),
      el("p",  { class: "modal-body" },  "This modal is the TypeScript equivalent of the Synth demo."),
      el("button", { class: "btn btn-primary modal-close-btn", id: "modal-close-ts" }, "Close")
    )
  )

  const openBtn = el("button", { class: "btn btn-primary" }, "Open Modal")

  openBtn.addEventListener("click", () => {
    state = modal_open("Hello from TypeScript", "Pure state logic")
    overlay.style.display = "flex"
  })

  document.getElementById("modal-close-ts")?.addEventListener("click", () => {
    state = modal_close(state)
    overlay.style.display = "none"
  })

  overlay.addEventListener("click", (e: Event) => {
    if (e.target === overlay) {
      state = modal_close(state)
      overlay.style.display = "none"
    }
  })

  document.body.appendChild(overlay)
  mount(containerId, openBtn)
}
`,
  js:  `
const CounterState = (count, min, max) => ({ count, min, max });

const ValidationResult = (valid, message, value) => ({ valid, message, value });

const ModalState = (open, title, body) => ({ open, title, body });

const Player = (name, score, active) => ({ name, score, active });

const counter_make = (min, max, initial) => ({count: \$clamp(initial, min, max), min, max});

const counter_inc = (state) => ({...state, count: Math.min(state.count + 1, state.max)});

const counter_dec = (state) => ({...state, count: Math.max(state.count - 1, state.min)});

const counter_can_inc = (state) => state.count < state.max;

const counter_can_dec = (state) => state.count > state.min;

/**
 * @param {CounterState} state
 * @returns {string}
 */
const counter_display = (state) => {
  let n = state.count;
  return ((_m) => (_m > 0) ? \`+\${n}\` : (_m < 0) ? \`\${n}\` : "0")(n);
};

const is_valid_email = (email) => __validate_EmailAddress(email);

/**
 * @param {string} email
 * @returns {ValidationResult}
 */
const validate_email = (email) => ((_m) => (_m === 0) ? {valid: false, message: "Email is required", value: email} : ((_m) => (_m === true) ? {valid: true, message: "Looks good!", value: email} : (_m === false) ? {valid: false, message: "Enter a valid email address", value: email} : undefined)(is_valid_email(email)))(email.length);

const validation_css_class = (result) => result.valid ? "field-valid" : result.value.length === 0 ? "field-empty" : "field-invalid";

const toggle_flip = (state) => !state;

const toggle_label = (state, onLabel, offLabel) => state ? onLabel : offLabel;

const toggle_css_class = (state, baseClass) => state ? \`\${baseClass} \${baseClass}--on\` : \`\${baseClass} \${baseClass}--off\`;

const theme_class = (name) => \`theme-\${name}\`;

const theme_next = (current, available) => available[(available.indexOf(current) + 1) % available.length];

/**
 * @param {ThemeName} name
 * @returns {string}
 */
const theme_label = (name) => ((_m) => (_m === "light") ? "Light" : (_m === "dark") ? "Dark" : (_m === "synthwave") ? "Synthwave" : name)(name);

const modal_open = (title, body) => ({open: true, title, body});

const modal_close = (state) => ({...state, open: false});

/**
 * @param {EmailAddress} email
 * @param {NonEmptyString} name
 * @returns {string}
 */
const send_welcome = (email, name) => \`Welcome, \${name}! A confirmation has been sent to \${email}.\`;

/**
 * @param {NonEmptyString} label
 * @param {Score} value
 * @returns {string}
 */
const format_score = (label, value) => \`\${label}: \${value}/100\`;

/**
 * @param {CounterState} states
 * @returns {number}
 */
const counter_history_total = (states) => \$sum(\$map(states, (__x) => __x.count));

/**
 * @param {Player} players
 * @returns {string}
 */
const top_players = (players) => \$map(\$filter(players, (__x) => __x.active), (__x) => __x.name);

/**
 * @param {Player} players
 * @returns {number}
 */
const total_score = (players) => \$sum(\$map(players, (__x) => __x.score));

const fibonacci = (() => {
  const __cache = new Map();
  return (n) => {
    const __key = JSON.stringify([n]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return ((_m) => (_m === 0) ? 0 : (_m === 1) ? 1 : fibonacci(n - 1) + fibonacci(n - 2))(n);
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

const triangle_number = (() => {
  const __cache = new Map();
  return (n) => {
    const __key = JSON.stringify([n]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return n * (n + 1) / 2;
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * @param {string} emails
 * @returns {ValidationResult}
 */
const validate_email_batch = (emails) => \$map(emails, validate_email);

/**
 * @param {string} emails
 * @returns {number}
 */
const count_valid_emails = (emails) => \$count(\$filter(emails, is_valid_email));

/**
 * @param {string} emails
 * @returns {string}
 */
const first_invalid_email = (emails) => \$find(emails, (e) => !is_valid_email(e)) ?? "";

/**
 * @param {string} themes
 * @returns {string}
 */
const theme_options = (themes) => \$map(themes, theme_label);

/**
 * @param {CounterState} states
 * @returns {boolean}
 */
const any_at_max = (states) => \$any(states, (s) => s.count === s.max);

/**
 * @param {string} email
 * @returns {boolean}
 */
const debug_validate = (email) => {
  let result = is_valid_email(email);
  console.log("debug_validate:", email, "->", result);
  return result;
};

/**
 * @param {string} tag
 * @param {object} attrs
 * @param {*} ...children
 * @returns {Element}
 */
const el = (tag, attrs, ...children) => {
  let e = document.createElement(tag);
  Object.entries(attrs).forEach(([k, v]) => (() => {
    if (k === "class") {
      return e.className = v;
    } else if (k === "disabled") {
      return e.disabled = v;
    } else if (k === "checked") {
      return e.checked = v;
    } else if (k.startsWith("on")) {
      return e.addEventListener(k.slice(2).toLowerCase(), v);
    } else if (k === "placeholder") {
      return e.placeholder = v;
    } else if (k === "type") {
      return e.type = v;
    } else if (k === "value") {
      return e.value = v;
    } else if (k === "id") {
      return e.id = v;
    } else if (k === "for") {
      return e.setAttribute("for", v);
    } else {
      return e.setAttribute(k, String(v));
    }
})());
  \$flat(children).forEach((child) => (() => {
    if (typeof child === "string") {
      return e.appendChild(document.createTextNode(child));
    } else if (child instanceof Node) {
      return e.appendChild(child);
    }
})());
  return e;
};

/**
 * @param {string} containerId
 * @param {Element} child
 * @returns {void}
 */
const mount = (containerId, child) => {
  let container = document.getElementById(containerId);
  return container.appendChild(child);
};

/**
 * @param {string} containerId
 * @returns {void}
 */
const render_counter = (containerId) => {
  let state = counter_make(-10, 10, 0);
  let display = el("span", {class: "counter-value"}, counter_display(state));
  let decBtn = el("button", {class: "btn btn-ghost"}, "−");
  let incBtn = el("button", {class: "btn btn-ghost"}, "+");
  decBtn.addEventListener("click", () => (() => {
    state = counter_dec(state);
    display.textContent = counter_display(state);
    decBtn.disabled = !counter_can_dec(state);
    return incBtn.disabled = !counter_can_inc(state);
})());
  incBtn.addEventListener("click", () => (() => {
    state = counter_inc(state);
    display.textContent = counter_display(state);
    decBtn.disabled = !counter_can_dec(state);
    return incBtn.disabled = !counter_can_inc(state);
})());
  return mount(containerId, el("div", {class: "counter-widget"}, decBtn, display, incBtn));
};

/**
 * @param {string} containerId
 * @returns {void}
 */
const render_email_validator = (containerId) => {
  let input = el("input", {type: "email", class: "input-field", placeholder: "you@example.com", id: "email-input"});
  let feedback = el("span", {class: "field-empty feedback-msg"}, "Enter your email");
  input.addEventListener("input", () => (() => {
    let result = validate_email(input.value);
    feedback.textContent = result.message;
    feedback.className = validation_css_class(result) + " feedback-msg";
    return input.className = "input-field " + validation_css_class(result);
})());
  return mount(containerId, el("div", {class: "validator-widget"}, el("label", {for: "email-input", class: "field-label"}, "Email Address"), input, feedback));
};

/**
 * @param {string} containerId
 * @param {string} onLabel
 * @param {string} offLabel
 * @returns {void}
 */
const render_toggle = (containerId, onLabel, offLabel) => {
  let state = false;
  let track = el("div", {class: toggle_css_class(state, "toggle-track")});
  let thumb = el("div", {class: "toggle-thumb"});
  let label = el("span", {class: "toggle-label"}, toggle_label(state, onLabel, offLabel));
  track.appendChild(thumb);
  let btn = el("button", {class: "toggle-btn"}, track, label);
  btn.addEventListener("click", () => (() => {
    state = toggle_flip(state);
    track.className = toggle_css_class(state, "toggle-track");
    return label.textContent = toggle_label(state, onLabel, offLabel);
})());
  return mount(containerId, btn);
};

/**
 * @param {string} containerId
 * @returns {void}
 */
const render_theme_switcher = (containerId) => {
  let themes = ["light", "dark", "synthwave"];
  let labels = theme_options(themes);
  let current = 0;
  document.body.className = theme_class(themes[current]);
  let lbl = el("span", {class: "theme-label"}, labels[current]);
  let ico = el("span", {class: "theme-icon"}, "◐");
  let btn = el("button", {class: "btn btn-theme"}, ico, lbl);
  btn.addEventListener("click", () => (() => {
    current = (current + 1) % themes.length;
    document.body.className = theme_class(themes[current]);
    return lbl.textContent = labels[current];
})());
  return mount(containerId, btn);
};

/**
 * @param {string} containerId
 * @returns {void}
 */
const render_modal_demo = (containerId) => {
  let state = modal_close({open: false, title: "", body: ""});
  let closeBtn = el("button", {class: "btn btn-primary modal-close-btn"}, "Close");
  let overlay = el("div", {class: "modal-overlay"}, el("div", {class: "modal-box"}, el("h3", {class: "modal-title"}, "Hello from Synth"), el("p", {class: "modal-body"}, "This modal state is managed by pure Synth functions. " + "Opening and closing are just state transitions — no framework needed."), closeBtn));
  let openBtn = el("button", {class: "btn btn-primary", id: "modal-open"}, "Open Modal");
  openBtn.addEventListener("click", () => (() => {
    state = modal_open("Hello from Synth", "Pure state logic");
    return overlay.style.display = "flex";
})());
  closeBtn.addEventListener("click", () => (() => {
    state = modal_close(state);
    return overlay.style.display = "none";
})());
  overlay.addEventListener("click", (e) => (() => {
    if (e.target === overlay) {
      state = modal_close(state);
      return overlay.style.display = "none";
    }
})());
  document.body.appendChild(overlay);
  return mount(containerId, openBtn);
};

`,
};
