const fs = require('fs')
const path = require('path')
const root = path.resolve(__dirname, '..')
const syn = fs.readFileSync(path.join(root, 'examples', 'rpg.syn'), 'utf8')
const js  = fs.readFileSync(path.join(root, 'demo', 'rpg.synth.js'), 'utf8')
const escape = s => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')
const out = `// Auto-generated by tools/embed_rpg.js
window.RPG_SOURCES = {
  syn: \`${escape(syn)}\`,
  js:  \`${escape(js)}\`,
};
`
fs.writeFileSync(path.join(root, 'demo', 'rpg.sources.js'), out, 'utf8')
console.log('✓ Wrote demo/rpg.sources.js')
