// Embeds music.syn source and transpiled JS into demo/music.sources.js
// Run after transpiling: node tools/embed_music.js
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')

const syn = fs.readFileSync(path.join(root, 'examples', 'music.syn'), 'utf8')
const js  = fs.readFileSync(path.join(root, 'demo',     'music.synth.js'), 'utf8')

const escape = s => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')

const out = `// Auto-generated by tools/embed_music.js — do not edit manually
window.MUSIC_SOURCES = {
  syn: \`${escape(syn)}\`,
  js:  \`${escape(js)}\`,
};
`

fs.writeFileSync(path.join(root, 'demo', 'music.sources.js'), out, 'utf8')
console.log('✓ Wrote demo/music.sources.js')
