// ─────────────────────────────────────────────────────────────────────────────
// Axon v0.2.0 — Standard library preamble
// Injected at the top of every transpiled JS file.
// All functions carry @intent + @pure @total — verified by the Axon checker.
// ─────────────────────────────────────────────────────────────────────────────

export const AXON_STDLIB = `
// ── Axon v0.4.0 stdlib ──────────────────────────────────────────────────────

/**
 * Apply fn to every element of xs and return the results.
 * @pure @total
 * @param {Array} xs
 * @param {Function} fn
 * @returns {Array}
 */
const map = (xs, fn) => xs.map(fn);

/**
 * Keep only elements of xs for which pred returns true.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {Array}
 */
const filter = (xs, pred) => xs.filter(pred);

/**
 * Reduce xs to a single value, starting from init.
 * @pure @total
 * @param {Array} xs
 * @param {*} init
 * @param {Function} fn
 * @returns {*}
 */
const fold = (xs, init, fn) => xs.reduce(fn, init);

/**
 * Apply a sequence of single-argument functions left to right.
 * @pure @total
 * @param {...Function} fns
 * @returns {Function}
 */
const pipe = (...fns) => (x) => fns.reduce((v, f) => f(v), x);

/**
 * Combine two arrays element-by-element into pairs.
 * @pure @total
 * @param {Array} xs
 * @param {Array} ys
 * @returns {Array}
 */
const zip = (xs, ys) => xs.map((x, i) => [x, ys[i]]);

/**
 * Produce an array of integers from start (inclusive) to end (exclusive).
 * @pure @total
 * @param {number} start
 * @param {number} end
 * @returns {number[]}
 */
const range = (start, end) => Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);

/**
 * Return the first element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const first = (xs) => xs[0];

/**
 * Return the last element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const last = (xs) => xs[xs.length - 1];

/**
 * Sum a numeric array.
 * @pure @total
 * @param {number[]} xs
 * @returns {number}
 */
const sum = (xs) => xs.reduce((a, b) => a + b, 0);

/**
 * Count elements matching pred, or total length if no pred given.
 * @pure @total
 * @param {Array} xs
 * @param {Function} [pred]
 * @returns {number}
 */
const count = (xs, pred) => pred ? xs.filter(pred).length : xs.length;

/**
 * True if any element satisfies pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const any = (xs, pred) => xs.some(pred);

/**
 * True if all elements satisfy pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const all = (xs, pred) => xs.every(pred);

/**
 * Flatten one level of nesting.
 * @pure @total
 * @param {Array} xs
 * @returns {Array}
 */
const flat = (xs) => xs.flat();

/**
 * Group an array into a Map by key function.
 * @pure @total
 * @param {Array} xs
 * @param {Function} keyFn
 * @returns {Map}
 */
const groupBy = (xs, keyFn) => xs.reduce((m, x) => {
  const k = keyFn(x);
  if (!m.has(k)) m.set(k, []);
  m.get(k).push(x);
  return m;
}, new Map());

/**
 * Return a new object with only the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const pick = (obj, keys) => Object.fromEntries(keys.filter(k => k in obj).map(k => [k, obj[k]]));

/**
 * Return a new object without the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const omit = (obj, keys) => Object.fromEntries(Object.entries(obj).filter(([k]) => !keys.includes(k)));

// ── Axon built-in constraint validators ─────────────────────────────────────
// Generated by 'type T = base where ...' declarations.

/**
 * Sort xs by the value returned by keyFn for each element (ascending).
 * Does not mutate the original array.
 * @pure @total
 */
const sort_by = (xs, keyFn) => [...xs].sort((a, b) => {
  const ka = keyFn(a), kb = keyFn(b);
  return ka < kb ? -1 : ka > kb ? 1 : 0;
});

/**
 * Sort xs in descending order by the value returned by keyFn.
 * Does not mutate the original array.
 * @pure @total
 */
const sort_by_desc = (xs, keyFn) => [...xs].sort((a, b) => {
  const ka = keyFn(a), kb = keyFn(b);
  return ka > kb ? -1 : ka < kb ? 1 : 0;
});

// ── v0.9.7 stdlib expansion ───────────────────────────────────────────────────

// ── String ───────────────────────────────────────────────────────────────────

/** Strip leading and trailing whitespace. @pure @total */
const trim = (s) => s.trim();

/** Split string s on separator sep. Returns an array of strings. @pure @total */
const split = (s, sep) => s.split(sep);

/** True if s starts with prefix. @pure @total */
const starts_with = (s, prefix) => s.startsWith(prefix);

/** True if s ends with suffix. @pure @total */
const ends_with = (s, suffix) => s.endsWith(suffix);

/** True if s contains substr (works for arrays too). @pure @total */
const contains = (s, sub) => s.includes(sub);

/** Convert string to UPPER CASE. @pure @total */
const to_upper = (s) => s.toUpperCase();

/** Convert string to lower case. @pure @total */
const to_lower = (s) => s.toLowerCase();

/** Replace every occurrence of from with to in s. @pure @total */
const replace_all = (s, from, to) => s.replaceAll(from, to);

/** Pad s on the left with padChar until it reaches length len. @pure @total */
const pad_start = (s, len, padChar = ' ') => s.padStart(len, padChar);

/** Pad s on the right with padChar until it reaches length len. @pure @total */
const pad_end = (s, len, padChar = ' ') => s.padEnd(len, padChar);

// ── Array ────────────────────────────────────────────────────────────────────

/** Return the smallest value in xs. @pure @total */
const min = (xs) => xs.reduce((a, b) => a < b ? a : b);

/** Return the largest value in xs. @pure @total */
const max = (xs) => xs.reduce((a, b) => a > b ? a : b);

/** Return the element of xs for which keyFn returns the smallest value. @pure @total */
const min_by = (xs, keyFn) => xs.reduce((a, b) => keyFn(a) <= keyFn(b) ? a : b);

/** Return the element of xs for which keyFn returns the largest value. @pure @total */
const max_by = (xs, keyFn) => xs.reduce((a, b) => keyFn(a) >= keyFn(b) ? a : b);

/** Return the first n elements of xs. @pure @total */
const take = (xs, n) => xs.slice(0, n);

/** Return xs with the first n elements removed. @pure @total */
const drop = (xs, n) => xs.slice(n);

/** Return a new array with duplicate values removed (preserves first occurrence). @pure @total */
const uniq = (xs) => [...new Set(xs)];

/** Split xs into consecutive chunks of size n. Last chunk may be smaller. @pure @total */
const chunk = (xs, n) => {
  const out = [];
  for (let i = 0; i < xs.length; i += n) out.push(xs.slice(i, i + n));
  return out;
};

/** Map each element to an array then flatten one level. @pure @total */
const flat_map = (xs, fn) => xs.flatMap(fn);

/** Return xs with the element at index i replaced by val. @pure @total */
const set_at = (xs, i, val) => [...xs.slice(0, i), val, ...xs.slice(i + 1)];

/** Reverse an array without mutating it. @pure @total */
const reverse = (xs) => [...xs].reverse();

/** Sum xs using a numeric key function, or directly if xs is numeric. @pure @total */
const sum_by = (xs, keyFn) => xs.reduce((acc, x) => acc + keyFn(x), 0);

// ── Math ─────────────────────────────────────────────────────────────────────

/** Clamp x to the range [lo, hi]. @pure @total */
const clamp = (x, lo, hi) => Math.max(lo, Math.min(hi, x));

/** Absolute value. @pure @total */
const abs = (x) => Math.abs(x);

/** Round to nearest integer. @pure @total */
const round = (x) => Math.round(x);

/** Round down to nearest integer. @pure @total */
const floor = (x) => Math.floor(x);

/** Round up to nearest integer. @pure @total */
const ceil = (x) => Math.ceil(x);

/** x raised to the power of exp. @pure @total */
const pow = (x, exp) => Math.pow(x, exp);

/** Square root of x. @pure @total */
const sqrt = (x) => Math.sqrt(x);

/** Random float in [0, 1). Not pure — use sparingly. */
const random = () => Math.random();

/** Random integer in [lo, hi] inclusive. Not pure. */
const random_int = (lo, hi) => Math.floor(Math.random() * (hi - lo + 1)) + lo;

const __axon_presets = {
  email:   /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/,
  url:     /^https?:\\/\\//,
  uuid:    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  alpha:   /^[a-zA-Z]+$/,
  alnum:   /^[a-zA-Z0-9]+$/,
  numeric: /^[0-9]+$/,
  slug:    /^[a-z0-9-]+$/,
  hex:     /^#?[0-9a-fA-F]{3,8}$/,
};

// ── Axon v0.6.0 Result type ──────────────────────────────────────────────────
// Result<T> = Ok { value: T } | Err { message: string }
// Constructors and helpers available in every Axon program.

/**
 * Wrap a value in Ok. Use as the success return of a @throws function.
 * @pure @total
 * @param {*} value
 * @returns {{ tag: 'Ok', value: * }}
 */
const ok = (value) => ({ tag: 'Ok', value });

/**
 * Wrap a message in Err. Use as the failure return of a @throws function.
 * @pure @total
 * @param {string} message
 * @returns {{ tag: 'Err', message: string }}
 */
const err = (message) => ({ tag: 'Err', message });

/**
 * True if result is Ok.
 * @pure @total
 * @param {{ tag: string }} r
 * @returns {boolean}
 */
const is_ok = (r) => r != null && r.tag === 'Ok';

/**
 * True if result is Err.
 * @pure @total
 * @param {{ tag: string }} r
 * @returns {boolean}
 */
const is_err = (r) => r != null && r.tag === 'Err';

/**
 * Unwrap Ok value — throws if Err.
 * @param {{ tag: string, value: *, message: string }} r
 * @returns {*}
 */
const unwrap = (r) => {
  if (r != null && r.tag === 'Ok') return r.value;
  throw new Error(r != null ? r.message : 'unwrap called on null');
};

/**
 * Unwrap Ok value, or return fallback if Err.
 * @pure @total
 * @param {{ tag: string, value: * }} r
 * @param {*} fallback
 * @returns {*}
 */
const unwrap_or = (r, fallback) => (r != null && r.tag === 'Ok') ? r.value : fallback;

// ── Axon v0.8.0 Async helpers ────────────────────────────────────────────────

/**
 * Return a Promise that resolves after ms milliseconds.
 * Use with await inside async fn declarations.
 * @param {number} ms  Duration in milliseconds
 * @returns {Promise<void>}
 */
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// ── Axon v0.4.0 test runner ──────────────────────────────────────────────────
// @test declarations push entries here. Call __runAxonTests() to execute them.
// Also exposed on globalThis so the CLI's vm context can access it.

const __axon_tests = [];

/**
 * Run all registered @test declarations. Returns a result summary.
 * @returns {{ passed: number, failed: number, total: number, results: Array }}
 */
const __runAxonTests = () => {
  let passed = 0, failed = 0;
  const results = [];
  for (const t of __axon_tests) {
    try {
      const ok = !!t.fn();
      if (ok) {
        passed++;
        results.push({ ok: true,  desc: t.desc });
      } else {
        failed++;
        results.push({ ok: false, desc: t.desc, error: 'assertion returned false' });
      }
    } catch(e) {
      failed++;
      results.push({ ok: false, desc: t.desc, error: String(e) });
    }
  }
  return { passed, failed, total: passed + failed, results };
};
// Expose on globalThis so the Node CLI vm context and browser window can both access it
if (typeof globalThis !== 'undefined') {
  globalThis.__axon_tests = __axon_tests;
  globalThis.__runAxonTests = __runAxonTests;
}

`
